-- ============================================
-- SQL Queries Generated on 2026-08-23 19:54:10.761807
-- ============================================
-- These queries can be copied and executed directly
-- Subqueries are used to automatically resolve IDs
-- ============================================


-- ============================================
-- Simulator: AI in Your Hands: Healthy, Practical, Self-Sufficient Use
-- ============================================
INSERT INTO simulator (title, description, level, localisation, estimated_duration, created_at) VALUES ('AI in Your Hands: Healthy, Practical, Self-Sufficient Use', 'No description', 'core', 'Work / Home', 15, '2026-08-23 19:54:10.760931');

-- Simulator Tags
INSERT INTO simulator_tag (name) VALUES ('AI literacy');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_tag WHERE name = 'AI literacy' LIMIT 1));
INSERT INTO simulator_tag (name) VALUES ('Digital skills');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_tag WHERE name = 'Digital skills' LIMIT 1));
INSERT INTO simulator_tag (name) VALUES ('Healthy technology use');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_tag WHERE name = 'Healthy technology use' LIMIT 1));
INSERT INTO simulator_tag (name) VALUES ('Self-sufficiency');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_tag WHERE name = 'Self-sufficiency' LIMIT 1));
INSERT INTO simulator_tag (name) VALUES ('Prompt writing');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_tag WHERE name = 'Prompt writing' LIMIT 1));
INSERT INTO simulator_tag (name) VALUES ('Privacy');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_tag WHERE name = 'Privacy' LIMIT 1));

-- Simulator Metrics
INSERT INTO simulator_metric (name) VALUES ('Autonomy');
INSERT INTO simulator_contains_metric (simulator_id, metric_id) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1));
INSERT INTO simulator_metric (name) VALUES ('Effectiveness');
INSERT INTO simulator_contains_metric (simulator_id, metric_id) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1));
INSERT INTO simulator_metric (name) VALUES ('Discernment');
INSERT INTO simulator_contains_metric (simulator_id, metric_id) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1));

-- ============================================
-- Card 1
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), 1, 'Phase 1: The Blank Page', 'Where to start', 'Five minutes of your own thinking before AI is worth more than an hour of editing AI''s output afterwards. Direction comes from you. Typing can come from anywhere.', 'This first scenario tests the single most important AI habit: whether the learner uses AI as a first replacement for thinking, or as a second pair of hands after their own thinking has started. It sets the tone for the rest of the simulator: the goal is not to use AI more or less, but to use it after your own direction is clear.');

-- Component 1 for Card 0
INSERT INTO component_text (content) VALUES ('You need to write a 500-word summary of a difficult project for your manager by tomorrow. It is 9 in the evening. You are tired. You could open a new document, or you could open an AI chat window. Where do you begin?');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 1: The Blank Page' AND owner_id = (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use') LIMIT 1), 'text', 1, LAST_INSERT_ID());

-- Component 2 for Card 0
INSERT INTO component_mcq (question) VALUES ('You need to write a 500-word summary of a difficult project for your manager by tomorrow. It is 9 in the evening. You are tired. You could open a new document, or you could open an AI chat window. Where do you begin?');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You need to write a 500-word summary of a difficult project for your manager by tomorrow. It is 9 in the evening. You are tired. You could open a new document, or you could open an AI chat window. Where do you begin?' ORDER BY id DESC LIMIT 1), 'You open the AI chat first and ask it to write the whole summary for you. You will edit later, but right now you just need something on the page.', 'Understandable at 9pm, but this is the pattern that quietly erodes self-sufficiency over time. When AI writes first, your own thinking never fully forms, and the edits you make later are shallow because you never held the structure in your head. There is a small middle path that costs almost nothing: 5 minutes of your own rough thoughts first.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You need to write a 500-word summary of a difficult project for your manager by tomorrow. It is 9 in the evening. You are tired. You could open a new document, or you could open an AI chat window. Where do you begin?') 
     AND option_text = 'You open the AI chat first and ask it to write the whole summary for you. You will edit later, but right now you just need something on the page.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), -15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You need to write a 500-word summary of a difficult project for your manager by tomorrow. It is 9 in the evening. You are tired. You could open a new document, or you could open an AI chat window. Where do you begin?') 
     AND option_text = 'You open the AI chat first and ask it to write the whole summary for you. You will edit later, but right now you just need something on the page.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), -5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You need to write a 500-word summary of a difficult project for your manager by tomorrow. It is 9 in the evening. You are tired. You could open a new document, or you could open an AI chat window. Where do you begin?') 
     AND option_text = 'You open the AI chat first and ask it to write the whole summary for you. You will edit later, but right now you just need something on the page.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), -5);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You need to write a 500-word summary of a difficult project for your manager by tomorrow. It is 9 in the evening. You are tired. You could open a new document, or you could open an AI chat window. Where do you begin?' ORDER BY id DESC LIMIT 1), 'You spend 5 minutes writing a scrappy bullet-point outline of what you actually want to say. Then you paste it into the AI chat and ask it to help you turn it into a clean 500-word summary in your voice.', 'Excellent. Those 5 minutes are the most important minutes in the whole task. You held the direction, AI handled the typing. The output will sound like you because you gave it the raw material of your own thinking. This is exactly what healthy, effective AI use looks like.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You need to write a 500-word summary of a difficult project for your manager by tomorrow. It is 9 in the evening. You are tired. You could open a new document, or you could open an AI chat window. Where do you begin?') 
     AND option_text = 'You spend 5 minutes writing a scrappy bullet-point outline of what you actually want to say. Then you paste it into the AI chat and ask it to help you turn it into a clean 500-word summary in your voice.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), 20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You need to write a 500-word summary of a difficult project for your manager by tomorrow. It is 9 in the evening. You are tired. You could open a new document, or you could open an AI chat window. Where do you begin?') 
     AND option_text = 'You spend 5 minutes writing a scrappy bullet-point outline of what you actually want to say. Then you paste it into the AI chat and ask it to help you turn it into a clean 500-word summary in your voice.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), 20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You need to write a 500-word summary of a difficult project for your manager by tomorrow. It is 9 in the evening. You are tired. You could open a new document, or you could open an AI chat window. Where do you begin?') 
     AND option_text = 'You spend 5 minutes writing a scrappy bullet-point outline of what you actually want to say. Then you paste it into the AI chat and ask it to help you turn it into a clean 500-word summary in your voice.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), 15);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You need to write a 500-word summary of a difficult project for your manager by tomorrow. It is 9 in the evening. You are tired. You could open a new document, or you could open an AI chat window. Where do you begin?' ORDER BY id DESC LIMIT 1), 'You refuse to use AI at all. Writing the whole thing yourself is the only way to keep your skills sharp.', 'This preserves autonomy fully but pays a real cost. You will spend two hours on a task that should take 45 minutes, and you will still send a tired 9pm summary. Self-sufficiency does not mean refusing tools. It means using them from a position of clarity, not from a position of dependence. The middle path in option 2 protects both your time and your voice.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You need to write a 500-word summary of a difficult project for your manager by tomorrow. It is 9 in the evening. You are tired. You could open a new document, or you could open an AI chat window. Where do you begin?') 
     AND option_text = 'You refuse to use AI at all. Writing the whole thing yourself is the only way to keep your skills sharp.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), 5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You need to write a 500-word summary of a difficult project for your manager by tomorrow. It is 9 in the evening. You are tired. You could open a new document, or you could open an AI chat window. Where do you begin?') 
     AND option_text = 'You refuse to use AI at all. Writing the whole thing yourself is the only way to keep your skills sharp.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), -15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You need to write a 500-word summary of a difficult project for your manager by tomorrow. It is 9 in the evening. You are tired. You could open a new document, or you could open an AI chat window. Where do you begin?') 
     AND option_text = 'You refuse to use AI at all. Writing the whole thing yourself is the only way to keep your skills sharp.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), 0);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 1: The Blank Page' AND owner_id = (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use') LIMIT 1), 'mcq', 2, LAST_INSERT_ID());

-- ============================================
-- Card 2
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), 2, 'Phase 2: The Confident Answer', 'Verify before you trust', 'AI is confident by default. That does not make it correct. Verify anything that would cost you real money, time, or reputation if it turned out to be wrong.', 'This scenario teaches the most important AI habit for cost-avoidance: verification. AI confidence is not correlated with correctness, and unverified AI answers on regulated topics are one of the most common ways women lose real money or make real mistakes. The goal is not fear, it is a calm verification habit.');

-- Component 1 for Card 1
INSERT INTO component_text (content) VALUES ('You ask an AI a specific question about Belgian tax rules for freelancers, because you are considering starting a small side project. The AI gives you a detailed, confident, professional-sounding answer with specific percentages, deadlines, and references to article numbers. What do you do next?');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 2: The Confident Answer' AND owner_id = (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use') LIMIT 1), 'text', 1, LAST_INSERT_ID());

-- Component 2 for Card 1
INSERT INTO component_mcq (question) VALUES ('You ask an AI a specific question about Belgian tax rules for freelancers, because you are considering starting a small side project. The AI gives you a detailed, confident, professional-sounding answer with specific percentages, deadlines, and references to article numbers. What do you do next?');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You ask an AI a specific question about Belgian tax rules for freelancers, because you are considering starting a small side project. The AI gives you a detailed, confident, professional-sounding answer with specific percentages, deadlines, and references to article numbers. What do you do next?' ORDER BY id DESC LIMIT 1), 'The answer looks professional and specific. You trust it and start planning your side project based on the numbers it gave you.', 'This is the single most common AI mistake. AI models are fluent by design; fluency and correctness are not the same thing. AI regularly invents specific numbers, dates, article references, and even whole citations that sound completely real. On something like tax rules, one wrong percentage can cost you thousands of euros and a stressful conversation with your accountant. Verify before you act.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You ask an AI a specific question about Belgian tax rules for freelancers, because you are considering starting a small side project. The AI gives you a detailed, confident, professional-sounding answer with specific percentages, deadlines, and references to article numbers. What do you do next?') 
     AND option_text = 'The answer looks professional and specific. You trust it and start planning your side project based on the numbers it gave you.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), -5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You ask an AI a specific question about Belgian tax rules for freelancers, because you are considering starting a small side project. The AI gives you a detailed, confident, professional-sounding answer with specific percentages, deadlines, and references to article numbers. What do you do next?') 
     AND option_text = 'The answer looks professional and specific. You trust it and start planning your side project based on the numbers it gave you.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), -5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You ask an AI a specific question about Belgian tax rules for freelancers, because you are considering starting a small side project. The AI gives you a detailed, confident, professional-sounding answer with specific percentages, deadlines, and references to article numbers. What do you do next?') 
     AND option_text = 'The answer looks professional and specific. You trust it and start planning your side project based on the numbers it gave you.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), -20);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You ask an AI a specific question about Belgian tax rules for freelancers, because you are considering starting a small side project. The AI gives you a detailed, confident, professional-sounding answer with specific percentages, deadlines, and references to article numbers. What do you do next?' ORDER BY id DESC LIMIT 1), 'You use the AI answer as a starting orientation only. You verify the specific numbers on the official FPS Finance / SPF Finances website, or check with an accountant, before making any decision.', 'This is exactly the right habit. AI is excellent for getting you oriented to a topic quickly, so you know what to ask and what to look up. It is not a substitute for official sources, especially on anything involving money, health, law, or your family''s specific situation. You treated AI as a junior colleague, not as an authority. That is the whole skill.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You ask an AI a specific question about Belgian tax rules for freelancers, because you are considering starting a small side project. The AI gives you a detailed, confident, professional-sounding answer with specific percentages, deadlines, and references to article numbers. What do you do next?') 
     AND option_text = 'You use the AI answer as a starting orientation only. You verify the specific numbers on the official FPS Finance / SPF Finances website, or check with an accountant, before making any decision.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You ask an AI a specific question about Belgian tax rules for freelancers, because you are considering starting a small side project. The AI gives you a detailed, confident, professional-sounding answer with specific percentages, deadlines, and references to article numbers. What do you do next?') 
     AND option_text = 'You use the AI answer as a starting orientation only. You verify the specific numbers on the official FPS Finance / SPF Finances website, or check with an accountant, before making any decision.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You ask an AI a specific question about Belgian tax rules for freelancers, because you are considering starting a small side project. The AI gives you a detailed, confident, professional-sounding answer with specific percentages, deadlines, and references to article numbers. What do you do next?') 
     AND option_text = 'You use the AI answer as a starting orientation only. You verify the specific numbers on the official FPS Finance / SPF Finances website, or check with an accountant, before making any decision.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), 20);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You ask an AI a specific question about Belgian tax rules for freelancers, because you are considering starting a small side project. The AI gives you a detailed, confident, professional-sounding answer with specific percentages, deadlines, and references to article numbers. What do you do next?' ORDER BY id DESC LIMIT 1), 'You reject the answer entirely and decide not to use AI for any factual questions in the future. It cannot be trusted.', 'Understandable but too broad. AI is genuinely useful for orientation, first drafts, and language work; the problem is not that it is untrustworthy, it is that you have to know which parts to trust. Complete avoidance leaves a lot of usefulness on the table. The right move is not distrust; it is verification.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You ask an AI a specific question about Belgian tax rules for freelancers, because you are considering starting a small side project. The AI gives you a detailed, confident, professional-sounding answer with specific percentages, deadlines, and references to article numbers. What do you do next?') 
     AND option_text = 'You reject the answer entirely and decide not to use AI for any factual questions in the future. It cannot be trusted.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), 5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You ask an AI a specific question about Belgian tax rules for freelancers, because you are considering starting a small side project. The AI gives you a detailed, confident, professional-sounding answer with specific percentages, deadlines, and references to article numbers. What do you do next?') 
     AND option_text = 'You reject the answer entirely and decide not to use AI for any factual questions in the future. It cannot be trusted.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), -10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You ask an AI a specific question about Belgian tax rules for freelancers, because you are considering starting a small side project. The AI gives you a detailed, confident, professional-sounding answer with specific percentages, deadlines, and references to article numbers. What do you do next?') 
     AND option_text = 'You reject the answer entirely and decide not to use AI for any factual questions in the future. It cannot be trusted.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), 5);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 2: The Confident Answer' AND owner_id = (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use') LIMIT 1), 'mcq', 2, LAST_INSERT_ID());

-- ============================================
-- Card 3
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), 3, 'Phase 3: The First Answer', 'Shaping the output', 'The first prompt is never the best one. The second prompt, where you correct, refine, or narrow, is where AI actually becomes useful.', 'This scenario tests whether the learner treats AI as a one-shot machine or as a collaborator that improves through iteration. The single biggest skill separating effective AI users from frustrated ones is the willingness to give a short, specific correction rather than accepting the first output or throwing it away.');

-- Component 1 for Card 2
INSERT INTO component_text (content) VALUES ('You asked AI to help you draft a follow-up email to a potential client. The first answer comes back polished, but too formal, generic, and not quite in your voice. You need to send this in the next 20 minutes. What do you do?');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 3: The First Answer' AND owner_id = (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use') LIMIT 1), 'text', 1, LAST_INSERT_ID());

-- Component 2 for Card 2
INSERT INTO component_mcq (question) VALUES ('You asked AI to help you draft a follow-up email to a potential client. The first answer comes back polished, but too formal, generic, and not quite in your voice. You need to send this in the next 20 minutes. What do you do?');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You asked AI to help you draft a follow-up email to a potential client. The first answer comes back polished, but too formal, generic, and not quite in your voice. You need to send this in the next 20 minutes. What do you do?' ORDER BY id DESC LIMIT 1), 'You accept the first draft because you are short on time. It is not perfect but it is fine. You add your name and send it.', 'This is where most AI value is lost. The first prompt is almost never the best one; AI improves dramatically on the second and third pass. Sending the first draft means your client receives a message that sounds like every other AI-drafted email in their inbox. Two minutes of refinement would have made this genuinely useful.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to help you draft a follow-up email to a potential client. The first answer comes back polished, but too formal, generic, and not quite in your voice. You need to send this in the next 20 minutes. What do you do?') 
     AND option_text = 'You accept the first draft because you are short on time. It is not perfect but it is fine. You add your name and send it.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), -10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to help you draft a follow-up email to a potential client. The first answer comes back polished, but too formal, generic, and not quite in your voice. You need to send this in the next 20 minutes. What do you do?') 
     AND option_text = 'You accept the first draft because you are short on time. It is not perfect but it is fine. You add your name and send it.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), -15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to help you draft a follow-up email to a potential client. The first answer comes back polished, but too formal, generic, and not quite in your voice. You need to send this in the next 20 minutes. What do you do?') 
     AND option_text = 'You accept the first draft because you are short on time. It is not perfect but it is fine. You add your name and send it.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), -5);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You asked AI to help you draft a follow-up email to a potential client. The first answer comes back polished, but too formal, generic, and not quite in your voice. You need to send this in the next 20 minutes. What do you do?' ORDER BY id DESC LIMIT 1), 'You give AI a short, direct correction: ''This is too formal. Rewrite it warmer, shorter, in a conversational tone. Keep the main points but sound like a real person, not a corporate template.'' Then you make two small edits of your own and send.', 'Textbook. You just used AI the way it is designed to be used, as an iterative collaborator, not a one-shot generator. The correction was specific, the tone instruction was clear, and you kept the final edit in your own hands. This is where AI genuinely saves you time instead of just giving you something to fix.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to help you draft a follow-up email to a potential client. The first answer comes back polished, but too formal, generic, and not quite in your voice. You need to send this in the next 20 minutes. What do you do?') 
     AND option_text = 'You give AI a short, direct correction: ''This is too formal. Rewrite it warmer, shorter, in a conversational tone. Keep the main points but sound like a real person, not a corporate template.'' Then you make two small edits of your own and send.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to help you draft a follow-up email to a potential client. The first answer comes back polished, but too formal, generic, and not quite in your voice. You need to send this in the next 20 minutes. What do you do?') 
     AND option_text = 'You give AI a short, direct correction: ''This is too formal. Rewrite it warmer, shorter, in a conversational tone. Keep the main points but sound like a real person, not a corporate template.'' Then you make two small edits of your own and send.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), 20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to help you draft a follow-up email to a potential client. The first answer comes back polished, but too formal, generic, and not quite in your voice. You need to send this in the next 20 minutes. What do you do?') 
     AND option_text = 'You give AI a short, direct correction: ''This is too formal. Rewrite it warmer, shorter, in a conversational tone. Keep the main points but sound like a real person, not a corporate template.'' Then you make two small edits of your own and send.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), 15);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You asked AI to help you draft a follow-up email to a potential client. The first answer comes back polished, but too formal, generic, and not quite in your voice. You need to send this in the next 20 minutes. What do you do?' ORDER BY id DESC LIMIT 1), 'You throw out the AI draft entirely and write the whole email yourself from scratch. If AI cannot get it right first time, it is not worth the trouble.', 'Understandable frustration, but this is the pattern that leaves most AI value on the table. AI is not meant to get things right on the first prompt; the second prompt is where the real usefulness lives. Discarding the whole draft means you did the hardest part (starting) twice. A single correcting sentence would have unlocked most of what you needed.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to help you draft a follow-up email to a potential client. The first answer comes back polished, but too formal, generic, and not quite in your voice. You need to send this in the next 20 minutes. What do you do?') 
     AND option_text = 'You throw out the AI draft entirely and write the whole email yourself from scratch. If AI cannot get it right first time, it is not worth the trouble.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), 5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to help you draft a follow-up email to a potential client. The first answer comes back polished, but too formal, generic, and not quite in your voice. You need to send this in the next 20 minutes. What do you do?') 
     AND option_text = 'You throw out the AI draft entirely and write the whole email yourself from scratch. If AI cannot get it right first time, it is not worth the trouble.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), -10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to help you draft a follow-up email to a potential client. The first answer comes back polished, but too formal, generic, and not quite in your voice. You need to send this in the next 20 minutes. What do you do?') 
     AND option_text = 'You throw out the AI draft entirely and write the whole email yourself from scratch. If AI cannot get it right first time, it is not worth the trouble.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), 0);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 3: The First Answer' AND owner_id = (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use') LIMIT 1), 'mcq', 2, LAST_INSERT_ID());

-- ============================================
-- Card 4
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), 4, 'Phase 4: The Data Question', 'What to put in, what to keep out', 'The cost of AI is not the subscription. It is what happens to the data you paste in. Anonymise first; convenience second.', 'This scenario teaches the cost dimension most women learn about only after something goes wrong: what enters the AI chat is not always private. It reframes ''cost'' from subscription fees to something bigger, the real cost of data leakage, and teaches the specific habit of anonymising before pasting.');

-- Component 1 for Card 3
INSERT INTO component_text (content) VALUES ('A colleague is showing you a great new productivity trick: she drops confidential client documents into a free AI tool and asks it to summarise, translate, and analyse them. It is saving her hours. She suggests you do the same with your team''s internal reports. What do you do?');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 4: The Data Question' AND owner_id = (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use') LIMIT 1), 'text', 1, LAST_INSERT_ID());

-- Component 2 for Card 3
INSERT INTO component_mcq (question) VALUES ('A colleague is showing you a great new productivity trick: she drops confidential client documents into a free AI tool and asks it to summarise, translate, and analyse them. It is saving her hours. She suggests you do the same with your team''s internal reports. What do you do?');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'A colleague is showing you a great new productivity trick: she drops confidential client documents into a free AI tool and asks it to summarise, translate, and analyse them. It is saving her hours. She suggests you do the same with your team''s internal reports. What do you do?' ORDER BY id DESC LIMIT 1), 'You follow her lead and start doing the same thing. If everyone is doing it, it must be fine. The time savings are enormous.', 'Convenience is real, but the cost is invisible until it is not. Free AI tools often use your data to train their models unless you have specifically opted out; some tools store and log your inputs indefinitely. Uploading client documents, internal reports, personal health information, or identifying details can breach GDPR, your employment contract, or your client agreements, without you ever knowing. The trick is to use AI for the summary structure, not on the confidential content itself.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague is showing you a great new productivity trick: she drops confidential client documents into a free AI tool and asks it to summarise, translate, and analyse them. It is saving her hours. She suggests you do the same with your team''s internal reports. What do you do?') 
     AND option_text = 'You follow her lead and start doing the same thing. If everyone is doing it, it must be fine. The time savings are enormous.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), -10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague is showing you a great new productivity trick: she drops confidential client documents into a free AI tool and asks it to summarise, translate, and analyse them. It is saving her hours. She suggests you do the same with your team''s internal reports. What do you do?') 
     AND option_text = 'You follow her lead and start doing the same thing. If everyone is doing it, it must be fine. The time savings are enormous.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), 5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague is showing you a great new productivity trick: she drops confidential client documents into a free AI tool and asks it to summarise, translate, and analyse them. It is saving her hours. She suggests you do the same with your team''s internal reports. What do you do?') 
     AND option_text = 'You follow her lead and start doing the same thing. If everyone is doing it, it must be fine. The time savings are enormous.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), -20);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'A colleague is showing you a great new productivity trick: she drops confidential client documents into a free AI tool and asks it to summarise, translate, and analyse them. It is saving her hours. She suggests you do the same with your team''s internal reports. What do you do?' ORDER BY id DESC LIMIT 1), 'You use AI for the same kind of work but only after removing all identifying details, client names, financial specifics, and confidential information. You paste in an anonymised or restructured version, then apply the AI''s help back to the original yourself.', 'This is exactly the right approach. You kept the productivity gain, and you kept your privacy, contractual, and legal integrity intact. It takes an extra 3 minutes and saves you from risks that only become visible when they explode. This is what cost-aware AI use looks like: the real cost is not the subscription fee, it is what happens when data leaves.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague is showing you a great new productivity trick: she drops confidential client documents into a free AI tool and asks it to summarise, translate, and analyse them. It is saving her hours. She suggests you do the same with your team''s internal reports. What do you do?') 
     AND option_text = 'You use AI for the same kind of work but only after removing all identifying details, client names, financial specifics, and confidential information. You paste in an anonymised or restructured version, then apply the AI''s help back to the original yourself.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague is showing you a great new productivity trick: she drops confidential client documents into a free AI tool and asks it to summarise, translate, and analyse them. It is saving her hours. She suggests you do the same with your team''s internal reports. What do you do?') 
     AND option_text = 'You use AI for the same kind of work but only after removing all identifying details, client names, financial specifics, and confidential information. You paste in an anonymised or restructured version, then apply the AI''s help back to the original yourself.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague is showing you a great new productivity trick: she drops confidential client documents into a free AI tool and asks it to summarise, translate, and analyse them. It is saving her hours. She suggests you do the same with your team''s internal reports. What do you do?') 
     AND option_text = 'You use AI for the same kind of work but only after removing all identifying details, client names, financial specifics, and confidential information. You paste in an anonymised or restructured version, then apply the AI''s help back to the original yourself.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), 20);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'A colleague is showing you a great new productivity trick: she drops confidential client documents into a free AI tool and asks it to summarise, translate, and analyse them. It is saving her hours. She suggests you do the same with your team''s internal reports. What do you do?' ORDER BY id DESC LIMIT 1), 'You decide not to use AI for work documents at all. It is safer to just do things the old way.', 'This protects privacy fully but pays a real productivity cost. There is a middle path: use AI on anonymised versions of your work, or use tools where your organisation has an enterprise agreement with proper data guarantees. Blanket avoidance leaves you falling further behind colleagues who are learning safe practical use.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague is showing you a great new productivity trick: she drops confidential client documents into a free AI tool and asks it to summarise, translate, and analyse them. It is saving her hours. She suggests you do the same with your team''s internal reports. What do you do?') 
     AND option_text = 'You decide not to use AI for work documents at all. It is safer to just do things the old way.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), 5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague is showing you a great new productivity trick: she drops confidential client documents into a free AI tool and asks it to summarise, translate, and analyse them. It is saving her hours. She suggests you do the same with your team''s internal reports. What do you do?') 
     AND option_text = 'You decide not to use AI for work documents at all. It is safer to just do things the old way.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), -15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague is showing you a great new productivity trick: she drops confidential client documents into a free AI tool and asks it to summarise, translate, and analyse them. It is saving her hours. She suggests you do the same with your team''s internal reports. What do you do?') 
     AND option_text = 'You decide not to use AI for work documents at all. It is safer to just do things the old way.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), 10);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 4: The Data Question' AND owner_id = (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use') LIMIT 1), 'mcq', 2, LAST_INSERT_ID());

-- ============================================
-- Card 5
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), 5, 'Phase 5: The Late Night', 'When to use AI, and when not to', 'AI can help you find words. It cannot hold you. Use it as the pen, not as the ear.', 'This scenario teaches the most important boundary in healthy AI use: the difference between using AI as a thinking assistant and using it as an emotional substitute. Late nights are when this boundary matters most, and when women are most likely to blur it. The goal is neither total reliance nor total avoidance, but conscious use.');

-- Component 1 for Card 4
INSERT INTO component_text (content) VALUES ('It is 11pm. You had a difficult conversation with someone close to you earlier this evening. You are still upset. You are alone. Your AI chat window is open on your laptop, and you are considering typing everything out and asking it to help you make sense of what happened. What do you do?');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 5: The Late Night' AND owner_id = (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use') LIMIT 1), 'text', 1, LAST_INSERT_ID());

-- Component 2 for Card 4
INSERT INTO component_mcq (question) VALUES ('It is 11pm. You had a difficult conversation with someone close to you earlier this evening. You are still upset. You are alone. Your AI chat window is open on your laptop, and you are considering typing everything out and asking it to help you make sense of what happened. What do you do?');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'It is 11pm. You had a difficult conversation with someone close to you earlier this evening. You are still upset. You are alone. Your AI chat window is open on your laptop, and you are considering typing everything out and asking it to help you make sense of what happened. What do you do?' ORDER BY id DESC LIMIT 1), 'You type everything out in detail, share names and full context, and let the AI walk you through it all night. It feels patient and non-judgmental in a way people rarely are.', 'AI can genuinely help you organise your thoughts, and there is nothing wrong with using it for that. But there are three specific risks late at night: you tend to share more identifying details than you should, you can build an emotional dependency on a tool that cannot actually remember or care about you, and you skip the harder step of taking your real feelings to a person who knows you. AI can be the pen; a trusted person is the ear.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is 11pm. You had a difficult conversation with someone close to you earlier this evening. You are still upset. You are alone. Your AI chat window is open on your laptop, and you are considering typing everything out and asking it to help you make sense of what happened. What do you do?') 
     AND option_text = 'You type everything out in detail, share names and full context, and let the AI walk you through it all night. It feels patient and non-judgmental in a way people rarely are.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), -20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is 11pm. You had a difficult conversation with someone close to you earlier this evening. You are still upset. You are alone. Your AI chat window is open on your laptop, and you are considering typing everything out and asking it to help you make sense of what happened. What do you do?') 
     AND option_text = 'You type everything out in detail, share names and full context, and let the AI walk you through it all night. It feels patient and non-judgmental in a way people rarely are.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), -5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is 11pm. You had a difficult conversation with someone close to you earlier this evening. You are still upset. You are alone. Your AI chat window is open on your laptop, and you are considering typing everything out and asking it to help you make sense of what happened. What do you do?') 
     AND option_text = 'You type everything out in detail, share names and full context, and let the AI walk you through it all night. It feels patient and non-judgmental in a way people rarely are.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), -15);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'It is 11pm. You had a difficult conversation with someone close to you earlier this evening. You are still upset. You are alone. Your AI chat window is open on your laptop, and you are considering typing everything out and asking it to help you make sense of what happened. What do you do?' ORDER BY id DESC LIMIT 1), 'You use AI only to help you organise your own thoughts, without identifying details, then close the laptop. You save the harder version of the conversation for tomorrow, with a friend, a partner, or a therapist who actually knows you.', 'This is exactly the right boundary. AI is very good at helping you find words when your feelings feel tangled; it is not a substitute for someone who has known you for years. You used the tool for what it does well and stopped where it stops being useful. That is healthy emotional autonomy in action.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is 11pm. You had a difficult conversation with someone close to you earlier this evening. You are still upset. You are alone. Your AI chat window is open on your laptop, and you are considering typing everything out and asking it to help you make sense of what happened. What do you do?') 
     AND option_text = 'You use AI only to help you organise your own thoughts, without identifying details, then close the laptop. You save the harder version of the conversation for tomorrow, with a friend, a partner, or a therapist who actually knows you.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), 20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is 11pm. You had a difficult conversation with someone close to you earlier this evening. You are still upset. You are alone. Your AI chat window is open on your laptop, and you are considering typing everything out and asking it to help you make sense of what happened. What do you do?') 
     AND option_text = 'You use AI only to help you organise your own thoughts, without identifying details, then close the laptop. You save the harder version of the conversation for tomorrow, with a friend, a partner, or a therapist who actually knows you.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is 11pm. You had a difficult conversation with someone close to you earlier this evening. You are still upset. You are alone. Your AI chat window is open on your laptop, and you are considering typing everything out and asking it to help you make sense of what happened. What do you do?') 
     AND option_text = 'You use AI only to help you organise your own thoughts, without identifying details, then close the laptop. You save the harder version of the conversation for tomorrow, with a friend, a partner, or a therapist who actually knows you.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), 15);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'It is 11pm. You had a difficult conversation with someone close to you earlier this evening. You are still upset. You are alone. Your AI chat window is open on your laptop, and you are considering typing everything out and asking it to help you make sense of what happened. What do you do?' ORDER BY id DESC LIMIT 1), 'You close the laptop without typing anything. AI is for work, not for feelings. You will manage tonight on your own.', 'This protects the emotional boundary fully, which is worth something. But AI can genuinely help you think more clearly when your head is spinning, without any real emotional cost, if you keep the boundaries in place. Refusing to use it for anything personal is overcorrecting. The middle path in option 2 uses the tool where it helps and stops where it does not.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is 11pm. You had a difficult conversation with someone close to you earlier this evening. You are still upset. You are alone. Your AI chat window is open on your laptop, and you are considering typing everything out and asking it to help you make sense of what happened. What do you do?') 
     AND option_text = 'You close the laptop without typing anything. AI is for work, not for feelings. You will manage tonight on your own.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), 10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is 11pm. You had a difficult conversation with someone close to you earlier this evening. You are still upset. You are alone. Your AI chat window is open on your laptop, and you are considering typing everything out and asking it to help you make sense of what happened. What do you do?') 
     AND option_text = 'You close the laptop without typing anything. AI is for work, not for feelings. You will manage tonight on your own.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), -5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is 11pm. You had a difficult conversation with someone close to you earlier this evening. You are still upset. You are alone. Your AI chat window is open on your laptop, and you are considering typing everything out and asking it to help you make sense of what happened. What do you do?') 
     AND option_text = 'You close the laptop without typing anything. AI is for work, not for feelings. You will manage tonight on your own.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), 10);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 5: The Late Night' AND owner_id = (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use') LIMIT 1), 'mcq', 2, LAST_INSERT_ID());

-- ============================================
-- Card 6
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), 6, 'Phase 6: The Almost-Ready Draft', 'Who wrote this?', 'A good AI user leaves every conversation still sounding like herself. The polish is not the point. The voice is.', 'This final scenario tests the deepest healthy-use skill: keeping your voice intact even when AI''s default voice sounds polished. It closes the simulator on the point that matters most, effective AI use is not about how much you rely on AI, it is about how much of you remains in the final output.');

-- Component 1 for Card 5
INSERT INTO component_text (content) VALUES ('You asked AI to write a personal introduction paragraph for your new professional profile. The output is polished, well-structured, and technically correct. But when you read it back to yourself, it does not really sound like you, it sounds like a version of you written by a stranger. What do you do?');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 6: The Almost-Ready Draft' AND owner_id = (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use') LIMIT 1), 'text', 1, LAST_INSERT_ID());

-- Component 2 for Card 5
INSERT INTO component_mcq (question) VALUES ('You asked AI to write a personal introduction paragraph for your new professional profile. The output is polished, well-structured, and technically correct. But when you read it back to yourself, it does not really sound like you, it sounds like a version of you written by a stranger. What do you do?');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You asked AI to write a personal introduction paragraph for your new professional profile. The output is polished, well-structured, and technically correct. But when you read it back to yourself, it does not really sound like you, it sounds like a version of you written by a stranger. What do you do?' ORDER BY id DESC LIMIT 1), 'You copy and paste the AI text into your profile as-is. It sounds professional, that is what matters. Your voice is not that different anyway.', 'This is the pattern that quietly makes people sound the same across the internet. Your voice is one of the few things that actually distinguishes you professionally; AI''s default voice is generic on purpose. Pasting AI-as-is into anything public gives up something small each time, until eventually your online presence sounds like everyone else''s. The polish is not the point; the sound of you is.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to write a personal introduction paragraph for your new professional profile. The output is polished, well-structured, and technically correct. But when you read it back to yourself, it does not really sound like you, it sounds like a version of you written by a stranger. What do you do?') 
     AND option_text = 'You copy and paste the AI text into your profile as-is. It sounds professional, that is what matters. Your voice is not that different anyway.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), -20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to write a personal introduction paragraph for your new professional profile. The output is polished, well-structured, and technically correct. But when you read it back to yourself, it does not really sound like you, it sounds like a version of you written by a stranger. What do you do?') 
     AND option_text = 'You copy and paste the AI text into your profile as-is. It sounds professional, that is what matters. Your voice is not that different anyway.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), -10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to write a personal introduction paragraph for your new professional profile. The output is polished, well-structured, and technically correct. But when you read it back to yourself, it does not really sound like you, it sounds like a version of you written by a stranger. What do you do?') 
     AND option_text = 'You copy and paste the AI text into your profile as-is. It sounds professional, that is what matters. Your voice is not that different anyway.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), -10);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You asked AI to write a personal introduction paragraph for your new professional profile. The output is polished, well-structured, and technically correct. But when you read it back to yourself, it does not really sound like you, it sounds like a version of you written by a stranger. What do you do?' ORDER BY id DESC LIMIT 1), 'You keep the structure AI gave you, then rewrite roughly half of the sentences in your own words, changing at least three specific phrases that felt too corporate or too generic. You end with your version, not the AI''s.', 'This is exactly the right balance. You kept the time-saving structural work AI did well, and you kept the part that matters most, the actual voice on the page. This is what healthy AI use produces: text that could not have existed without you, only faster. Your voice stayed intact.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to write a personal introduction paragraph for your new professional profile. The output is polished, well-structured, and technically correct. But when you read it back to yourself, it does not really sound like you, it sounds like a version of you written by a stranger. What do you do?') 
     AND option_text = 'You keep the structure AI gave you, then rewrite roughly half of the sentences in your own words, changing at least three specific phrases that felt too corporate or too generic. You end with your version, not the AI''s.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), 20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to write a personal introduction paragraph for your new professional profile. The output is polished, well-structured, and technically correct. But when you read it back to yourself, it does not really sound like you, it sounds like a version of you written by a stranger. What do you do?') 
     AND option_text = 'You keep the structure AI gave you, then rewrite roughly half of the sentences in your own words, changing at least three specific phrases that felt too corporate or too generic. You end with your version, not the AI''s.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), 20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to write a personal introduction paragraph for your new professional profile. The output is polished, well-structured, and technically correct. But when you read it back to yourself, it does not really sound like you, it sounds like a version of you written by a stranger. What do you do?') 
     AND option_text = 'You keep the structure AI gave you, then rewrite roughly half of the sentences in your own words, changing at least three specific phrases that felt too corporate or too generic. You end with your version, not the AI''s.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), 15);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You asked AI to write a personal introduction paragraph for your new professional profile. The output is polished, well-structured, and technically correct. But when you read it back to yourself, it does not really sound like you, it sounds like a version of you written by a stranger. What do you do?' ORDER BY id DESC LIMIT 1), 'You throw out the AI draft entirely and write the whole thing from scratch. Only your own words are worth putting on a professional profile.', 'This preserves your voice fully but pays a time cost that was probably unnecessary. The structural work AI did (paragraph flow, sentence variety, opening line) is not the part of you that needed to stay untouched. Editing something halfway there is often better and faster than starting again. The middle path in option 2 gives you both.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to write a personal introduction paragraph for your new professional profile. The output is polished, well-structured, and technically correct. But when you read it back to yourself, it does not really sound like you, it sounds like a version of you written by a stranger. What do you do?') 
     AND option_text = 'You throw out the AI draft entirely and write the whole thing from scratch. Only your own words are worth putting on a professional profile.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to write a personal introduction paragraph for your new professional profile. The output is polished, well-structured, and technically correct. But when you read it back to yourself, it does not really sound like you, it sounds like a version of you written by a stranger. What do you do?') 
     AND option_text = 'You throw out the AI draft entirely and write the whole thing from scratch. Only your own words are worth putting on a professional profile.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), -10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You asked AI to write a personal introduction paragraph for your new professional profile. The output is polished, well-structured, and technically correct. But when you read it back to yourself, it does not really sound like you, it sounds like a version of you written by a stranger. What do you do?') 
     AND option_text = 'You throw out the AI draft entirely and write the whole thing from scratch. Only your own words are worth putting on a professional profile.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), 5);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 6: The Almost-Ready Draft' AND owner_id = (SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use') LIMIT 1), 'mcq', 2, LAST_INSERT_ID());

-- ============================================
-- Feedback Tiers
-- ============================================

-- Feedback for metric 'Autonomy' (Score 0-49)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), 0, 49, 'You are curious about AI and willing to try new tools. That openness is a real starting point.', 'You tend to reach for AI before your own thinking has started. Over time this can quietly erode your writing voice, decision-making confidence, and sense that you can figure things out on your own.', 'For the next three tasks, spend 5 minutes on your own scrappy notes before opening AI. Even if the notes feel bad, keep them, then hand them to AI for shaping.', NULL, 'When autonomy is low, AI can silently take over the work your own thinking was meant to do. The A Brief Use of AI course gives you the specific practice of starting with your own rough thoughts first, so the AI''s output stays anchored to your voice and direction, not to a generic default.');

-- Feedback for metric 'Autonomy' (Score 50-85)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), 50, 85, 'You use AI as a collaborator, not a replacement. Your own thinking still leads the work.', 'You still let AI take over on high-effort or late-night tasks, when your own thinking would have added more value with a small extra investment of time.', 'Notice one moment this week when you reach for AI out of tiredness rather than genuine need. Try 5 minutes of your own notes first, and see what changes.', NULL, 'You already have a working relationship with AI. The next step is protecting that relationship in the moments you are most vulnerable to over-reliance, tiredness, emotional moments, high-pressure deadlines. The A Brief Use of AI course teaches the four boundaries that keep AI a tool in your hand instead of a hand you have quietly handed over.');

-- Feedback for metric 'Autonomy' (Score 85-100)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_metric WHERE name = 'Autonomy' LIMIT 1), 85, 100, 'You use AI often and still sound like yourself. Your voice, judgement, and human relationships are intact.', 'None. Just watch that your autonomy stays paired with practical use, avoiding AI entirely is not a mark of independence, it is a different cost.', 'Teach one woman in your life how to keep her voice when using AI. Show her one specific trick that works for you.', NULL, 'Autonomy in AI use is one of the most valuable skills you can pass on. The A Brief Use of AI course helps you articulate the practices you are already doing intuitively, so you can teach them to others and continue refining them in higher-stakes contexts where the boundary between helpful and harmful use gets subtler.');

-- Feedback for metric 'Effectiveness' (Score 0-49)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), 0, 49, 'You approach AI honestly, without pretending to know things you do not know. That honesty is a genuine strength.', 'You often accept the first AI answer as final, or discard it entirely when it disappoints. The most valuable part of AI use, iterative refinement, is where you are leaving the most value on the table.', 'The next time an AI answer disappoints you, do not delete it. Instead, write one specific correction (''shorter'', ''warmer'', ''in my voice'', ''more concrete''). See what the second answer becomes.', NULL, 'When effectiveness is low, the missing skill is almost always the same: prompt iteration. The A Brief Use of AI course teaches copy-ready prompts across work, home, and learning, plus the specific technique of correcting the first answer with a short direct instruction, the single practice that separates frustrated AI users from effective ones.');

-- Feedback for metric 'Effectiveness' (Score 50-85)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), 50, 85, 'You know how to give AI useful direction, and you iterate when the first answer is not quite right.', 'You still sometimes accept mediocre outputs when a small correction would unlock a much better version. You also sometimes forget to give AI enough context up front, which slows down the whole exchange.', 'Next time you write a prompt, add one sentence of context up front: who you are, what you are trying to achieve, and what tone or format you want. That one sentence often replaces three rounds of correction.', NULL, 'You have the core iteration skill already. The next step is upfront prompt clarity, giving AI enough context in the first message so the second round of correction is smaller. The A Brief Use of AI course walks through the specific ways to frame prompts for different kinds of tasks, so you get useful output faster and with less back-and-forth.');

-- Feedback for metric 'Effectiveness' (Score 85-100)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_metric WHERE name = 'Effectiveness' LIMIT 1), 85, 100, 'You get real, useful, voice-specific output from AI reliably. You know how to iterate, correct, and reshape.', 'None. Just watch that effectiveness does not tip into automation, the moments where you let AI do everything because it can, not because it should.', 'Pick one task this week that AI could technically do for you, but which is worth doing yourself for the practice or the ownership. Do that one by hand.', NULL, 'High effectiveness with AI is a rare and valuable capacity. The A Brief Use of AI course helps you deepen the strategic side of that capacity, knowing when to reach for AI and when to consciously not, so your effectiveness stays paired with judgement and does not become mere convenience.');

-- Feedback for metric 'Discernment' (Score 0-49)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), 0, 49, 'You are trusting and open to new tools, which is what makes learning possible in the first place.', 'You tend to accept AI answers without verifying, share more personal or confidential information than is safe, or reach for AI even when the task calls for something else (an official source, a human, silence). The cost of these habits is invisible until it is not.', 'Before your next AI conversation, ask yourself one question: ''if this answer were wrong, what would it cost me?'' If the answer is significant, plan to verify.', NULL, 'When discernment is low, small AI habits carry outsized risk: unverified facts, leaked data, wrong tool for the moment. The A Brief Use of AI course gives you the 3-step verification habit, the four healthy boundaries, and the specific test of when AI is the right tool and when it is not, all in about 15 minutes.');

-- Feedback for metric 'Discernment' (Score 50-85)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), 50, 85, 'You verify AI on important facts, and you generally know what to share and what not to.', 'You still sometimes get caught out on lower-stakes tasks, small factual claims you did not double-check, casual pasting of details you should have anonymised, using AI for things a quick search or a trusted colleague would have answered better.', 'Before pasting anything into AI this week, do one sanity check: ''would I be comfortable if this appeared publicly?'' If the answer is no, anonymise or restructure first.', NULL, 'You have working discernment on the biggest calls. The next step is applying the same care to the smaller, more frequent decisions where risk accumulates. The A Brief Use of AI course helps you build fast, everyday habits for privacy, verification, and picking the right tool, so discernment becomes automatic rather than effortful.');

-- Feedback for metric 'Discernment' (Score 85-100)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'AI in Your Hands: Healthy, Practical, Self-Sufficient Use'), (SELECT id FROM simulator_metric WHERE name = 'Discernment' LIMIT 1), 85, 100, 'You know when to use AI, when to verify, when to anonymise, and when to reach for something else entirely.', 'None. Just watch that discernment does not tip into over-caution, spending more time checking than the task warrants is its own kind of cost.', 'Share one specific verification habit with a colleague or friend who is newer to AI. Your instincts are the kind of thing most people learn only after making a mistake.', NULL, 'Strong discernment is one of the rarest AI skills, most people either trust too much or too little. The A Brief Use of AI course helps you refine and articulate the decision-making rules you are already applying, so you can teach them to others and continue calibrating them as AI tools change over the next few years.');

-- ============================================
-- End of generated queries
-- ============================================
