-- ============================================
-- SQL Queries Generated on 2026-08-23 19:54:10.755862
-- ============================================
-- These queries can be copied and executed directly
-- Subqueries are used to automatically resolve IDs
-- ============================================


-- ============================================
-- Simulator: Networking with Nerve: Assertive, Composed, Strategic, Kind
-- ============================================
INSERT INTO simulator (title, description, level, localisation, estimated_duration, created_at) VALUES ('Networking with Nerve: Assertive, Composed, Strategic, Kind', 'No description', 'core', 'Work / Community', 15, '2026-08-23 19:54:10.755028');

-- Simulator Tags
INSERT INTO simulator_tag (name) VALUES ('Networking');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_tag WHERE name = 'Networking' LIMIT 1));
INSERT INTO simulator_tag (name) VALUES ('Assertiveness');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_tag WHERE name = 'Assertiveness' LIMIT 1));
INSERT INTO simulator_tag (name) VALUES ('Emotional regulation');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_tag WHERE name = 'Emotional regulation' LIMIT 1));
INSERT INTO simulator_tag (name) VALUES ('Strategic warmth');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_tag WHERE name = 'Strategic warmth' LIMIT 1));
INSERT INTO simulator_tag (name) VALUES ('Professional relationships');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_tag WHERE name = 'Professional relationships' LIMIT 1));

-- Simulator Metrics
INSERT INTO simulator_metric (name) VALUES ('Assertiveness');
INSERT INTO simulator_contains_metric (simulator_id, metric_id) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1));
INSERT INTO simulator_metric (name) VALUES ('Composure');
INSERT INTO simulator_contains_metric (simulator_id, metric_id) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1));
INSERT INTO simulator_metric (name) VALUES ('Strategic warmth');
INSERT INTO simulator_contains_metric (simulator_id, metric_id) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1));

-- ============================================
-- Card 1
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), 1, 'Phase 1: Preparation', 'Before the room', 'Ten minutes of clear preparation is worth more than two hours of anxious rehearsal, or three days of pretending you''ll figure it out in the moment.', 'This first scenario tests whether the learner defaults to avoidance (''just show up''), healthy strategic preparation, or over-preparation as a form of anxiety. It sets the tone for the rest of the simulator: networking is a skill that rewards small deliberate steps, not spontaneity or perfectionism.');

-- Component 1 for Card 0
INSERT INTO component_text (content) VALUES ('It is Tuesday morning. A colleague has just invited you to a networking mixer this Thursday evening, 40 people from your industry will be there, including two people you have been hoping to meet for months. You have three days to prepare (or not). What do you do?');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 1: Preparation' AND owner_id = (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind') LIMIT 1), 'text', 1, LAST_INSERT_ID());

-- Component 2 for Card 0
INSERT INTO component_mcq (question) VALUES ('It is Tuesday morning. A colleague has just invited you to a networking mixer this Thursday evening, 40 people from your industry will be there, including two people you have been hoping to meet for months. You have three days to prepare (or not). What do you do?');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'It is Tuesday morning. A colleague has just invited you to a networking mixer this Thursday evening, 40 people from your industry will be there, including two people you have been hoping to meet for months. You have three days to prepare (or not). What do you do?' ORDER BY id DESC LIMIT 1), 'You decide to just show up on Thursday and see what happens. Preparing feels like overthinking, and you trust yourself to be spontaneous in the moment.', 'Spontaneity has its place, but at events like this it usually means falling back on ''so, what do you do?'' and small talk. The women who leave events with the connections they wanted almost always spent 10 minutes preparing first. This is not overthinking. It is respect for your own time.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is Tuesday morning. A colleague has just invited you to a networking mixer this Thursday evening, 40 people from your industry will be there, including two people you have been hoping to meet for months. You have three days to prepare (or not). What do you do?') 
     AND option_text = 'You decide to just show up on Thursday and see what happens. Preparing feels like overthinking, and you trust yourself to be spontaneous in the moment.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), -5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is Tuesday morning. A colleague has just invited you to a networking mixer this Thursday evening, 40 people from your industry will be there, including two people you have been hoping to meet for months. You have three days to prepare (or not). What do you do?') 
     AND option_text = 'You decide to just show up on Thursday and see what happens. Preparing feels like overthinking, and you trust yourself to be spontaneous in the moment.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), 0);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is Tuesday morning. A colleague has just invited you to a networking mixer this Thursday evening, 40 people from your industry will be there, including two people you have been hoping to meet for months. You have three days to prepare (or not). What do you do?') 
     AND option_text = 'You decide to just show up on Thursday and see what happens. Preparing feels like overthinking, and you trust yourself to be spontaneous in the moment.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), -10);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'It is Tuesday morning. A colleague has just invited you to a networking mixer this Thursday evening, 40 people from your industry will be there, including two people you have been hoping to meet for months. You have three days to prepare (or not). What do you do?' ORDER BY id DESC LIMIT 1), 'You spend 10 minutes on the three-question prep: one sentence on what you actually do, one thing you are genuinely curious about right now, and one thing you can offer to someone else.', 'Excellent. Those three questions do most of the work of the evening in advance. You will sound clearer, you will have real questions to ask, and you will stand out just by being one of the few people thinking ''what can I offer?'' instead of ''what can I get?''.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is Tuesday morning. A colleague has just invited you to a networking mixer this Thursday evening, 40 people from your industry will be there, including two people you have been hoping to meet for months. You have three days to prepare (or not). What do you do?') 
     AND option_text = 'You spend 10 minutes on the three-question prep: one sentence on what you actually do, one thing you are genuinely curious about right now, and one thing you can offer to someone else.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is Tuesday morning. A colleague has just invited you to a networking mixer this Thursday evening, 40 people from your industry will be there, including two people you have been hoping to meet for months. You have three days to prepare (or not). What do you do?') 
     AND option_text = 'You spend 10 minutes on the three-question prep: one sentence on what you actually do, one thing you are genuinely curious about right now, and one thing you can offer to someone else.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), 10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is Tuesday morning. A colleague has just invited you to a networking mixer this Thursday evening, 40 people from your industry will be there, including two people you have been hoping to meet for months. You have three days to prepare (or not). What do you do?') 
     AND option_text = 'You spend 10 minutes on the three-question prep: one sentence on what you actually do, one thing you are genuinely curious about right now, and one thing you can offer to someone else.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), 20);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'It is Tuesday morning. A colleague has just invited you to a networking mixer this Thursday evening, 40 people from your industry will be there, including two people you have been hoping to meet for months. You have three days to prepare (or not). What do you do?' ORDER BY id DESC LIMIT 1), 'You spend two hours researching every attendee on LinkedIn and drafting a mental script for each of the two people you want to meet. You want to be fully ready.', 'Preparation is helpful, but two hours of scripted rehearsal often produces the opposite of what you want. You will sound rigid, you will listen less, and you will notice every deviation from your script as a small failure. Ten minutes of clear prep beats two hours of anxious rehearsal.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is Tuesday morning. A colleague has just invited you to a networking mixer this Thursday evening, 40 people from your industry will be there, including two people you have been hoping to meet for months. You have three days to prepare (or not). What do you do?') 
     AND option_text = 'You spend two hours researching every attendee on LinkedIn and drafting a mental script for each of the two people you want to meet. You want to be fully ready.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), 5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is Tuesday morning. A colleague has just invited you to a networking mixer this Thursday evening, 40 people from your industry will be there, including two people you have been hoping to meet for months. You have three days to prepare (or not). What do you do?') 
     AND option_text = 'You spend two hours researching every attendee on LinkedIn and drafting a mental script for each of the two people you want to meet. You want to be fully ready.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), -10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It is Tuesday morning. A colleague has just invited you to a networking mixer this Thursday evening, 40 people from your industry will be there, including two people you have been hoping to meet for months. You have three days to prepare (or not). What do you do?') 
     AND option_text = 'You spend two hours researching every attendee on LinkedIn and drafting a mental script for each of the two people you want to meet. You want to be fully ready.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), 5);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 1: Preparation' AND owner_id = (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind') LIMIT 1), 'mcq', 2, LAST_INSERT_ID());

-- ============================================
-- Card 2
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), 2, 'Phase 2: The Opener', 'Starting the conversation', 'You do not need a perfect script. You need to open with something specific about them, and one real question. That is the whole trick.', 'This scenario tests the moment women most often lose networking opportunities, the small window right before an opener. The three actions represent the three dominant patterns: freeze/avoid, warm strategic opener, or self-focused pitch. It teaches that assertiveness and warmth are not opposites, they combine in the same 15 seconds.');

-- Component 1 for Card 1
INSERT INTO component_text (content) VALUES ('You arrive at the event. Across the room, you see one of the two people you were hoping to meet, a senior director in your field, standing alone for a moment with a glass of water. This is your window. What do you do?');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 2: The Opener' AND owner_id = (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind') LIMIT 1), 'text', 1, LAST_INSERT_ID());

-- Component 2 for Card 1
INSERT INTO component_mcq (question) VALUES ('You arrive at the event. Across the room, you see one of the two people you were hoping to meet, a senior director in your field, standing alone for a moment with a glass of water. This is your window. What do you do?');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You arrive at the event. Across the room, you see one of the two people you were hoping to meet, a senior director in your field, standing alone for a moment with a glass of water. This is your window. What do you do?' ORDER BY id DESC LIMIT 1), 'You freeze, tell yourself she looks busy, and go get a drink to buy yourself time. Maybe another moment will come naturally later.', 'That ''natural moment'' rarely arrives, the room fills up, other people approach her, the window closes. Freezing is human, but it is also the number one reason women leave events regretting the conversations they did not have. Nothing dramatic needed to be said. A simple ''hi, I''m [name], I really enjoyed your talk last month on X'' would have been enough.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You arrive at the event. Across the room, you see one of the two people you were hoping to meet, a senior director in your field, standing alone for a moment with a glass of water. This is your window. What do you do?') 
     AND option_text = 'You freeze, tell yourself she looks busy, and go get a drink to buy yourself time. Maybe another moment will come naturally later.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), -15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You arrive at the event. Across the room, you see one of the two people you were hoping to meet, a senior director in your field, standing alone for a moment with a glass of water. This is your window. What do you do?') 
     AND option_text = 'You freeze, tell yourself she looks busy, and go get a drink to buy yourself time. Maybe another moment will come naturally later.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), -10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You arrive at the event. Across the room, you see one of the two people you were hoping to meet, a senior director in your field, standing alone for a moment with a glass of water. This is your window. What do you do?') 
     AND option_text = 'You freeze, tell yourself she looks busy, and go get a drink to buy yourself time. Maybe another moment will come naturally later.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), -5);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You arrive at the event. Across the room, you see one of the two people you were hoping to meet, a senior director in your field, standing alone for a moment with a glass of water. This is your window. What do you do?' ORDER BY id DESC LIMIT 1), 'You walk over, extend a hand, and open with: ''Hi, I''m [name]. I know you don''t know me, I''ve been hoping to catch you because I really valued your recent post on X. What are you working on that you''re excited about right now?''', 'This is textbook. You named yourself, you named a specific reason (not generic flattery), and you closed with a real question about her, not about you. Almost no one at this event will open a conversation this well. You just made yourself memorable in 15 seconds.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You arrive at the event. Across the room, you see one of the two people you were hoping to meet, a senior director in your field, standing alone for a moment with a glass of water. This is your window. What do you do?') 
     AND option_text = 'You walk over, extend a hand, and open with: ''Hi, I''m [name]. I know you don''t know me, I''ve been hoping to catch you because I really valued your recent post on X. What are you working on that you''re excited about right now?''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), 20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You arrive at the event. Across the room, you see one of the two people you were hoping to meet, a senior director in your field, standing alone for a moment with a glass of water. This is your window. What do you do?') 
     AND option_text = 'You walk over, extend a hand, and open with: ''Hi, I''m [name]. I know you don''t know me, I''ve been hoping to catch you because I really valued your recent post on X. What are you working on that you''re excited about right now?''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You arrive at the event. Across the room, you see one of the two people you were hoping to meet, a senior director in your field, standing alone for a moment with a glass of water. This is your window. What do you do?') 
     AND option_text = 'You walk over, extend a hand, and open with: ''Hi, I''m [name]. I know you don''t know me, I''ve been hoping to catch you because I really valued your recent post on X. What are you working on that you''re excited about right now?''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), 20);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You arrive at the event. Across the room, you see one of the two people you were hoping to meet, a senior director in your field, standing alone for a moment with a glass of water. This is your window. What do you do?' ORDER BY id DESC LIMIT 1), 'You approach her and immediately launch into your elevator pitch: your background, your current role, the project you''re working on, and why you''d love to work with her someday.', 'You showed courage in approaching, which matters. But leading with your pitch tells her the conversation is about you, not her. Senior people meet a lot of pitchers. The women who make a real impression open with genuine curiosity about the other person''s work first.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You arrive at the event. Across the room, you see one of the two people you were hoping to meet, a senior director in your field, standing alone for a moment with a glass of water. This is your window. What do you do?') 
     AND option_text = 'You approach her and immediately launch into your elevator pitch: your background, your current role, the project you''re working on, and why you''d love to work with her someday.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), 10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You arrive at the event. Across the room, you see one of the two people you were hoping to meet, a senior director in your field, standing alone for a moment with a glass of water. This is your window. What do you do?') 
     AND option_text = 'You approach her and immediately launch into your elevator pitch: your background, your current role, the project you''re working on, and why you''d love to work with her someday.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), 0);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You arrive at the event. Across the room, you see one of the two people you were hoping to meet, a senior director in your field, standing alone for a moment with a glass of water. This is your window. What do you do?') 
     AND option_text = 'You approach her and immediately launch into your elevator pitch: your background, your current role, the project you''re working on, and why you''d love to work with her someday.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), -10);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 2: The Opener' AND owner_id = (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind') LIMIT 1), 'mcq', 2, LAST_INSERT_ID());

-- ============================================
-- Card 3
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), 3, 'Phase 3: The Dismissal', 'Not taking it personally', 'Someone''s rudeness is data about them, not about you. Composure is the skill of remembering that in real time.', 'Networking regularly involves people who are distracted, tired, or genuinely rude. This scenario teaches that the difference between women who build strong networks and those who don''t is not who gets treated well, it is how they respond when they''re treated badly. Composure, not confrontation, is the strategic move.');

-- Component 1 for Card 2
INSERT INTO component_text (content) VALUES ('You are three sentences into introducing your work when the person you are speaking with looks over your shoulder, half-waves at someone more senior, and says distractedly: ''sorry, what did you say your name was again?'', and then immediately: ''is Sarah here yet?''. What do you do?');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 3: The Dismissal' AND owner_id = (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind') LIMIT 1), 'text', 1, LAST_INSERT_ID());

-- Component 2 for Card 2
INSERT INTO component_mcq (question) VALUES ('You are three sentences into introducing your work when the person you are speaking with looks over your shoulder, half-waves at someone more senior, and says distractedly: ''sorry, what did you say your name was again?'', and then immediately: ''is Sarah here yet?''. What do you do?');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You are three sentences into introducing your work when the person you are speaking with looks over your shoulder, half-waves at someone more senior, and says distractedly: ''sorry, what did you say your name was again?'', and then immediately: ''is Sarah here yet?''. What do you do?' ORDER BY id DESC LIMIT 1), 'You feel a flash of embarrassment, mumble your name again, and quickly find an excuse to step away. This person clearly is not interested in you.', 'Understandable, but you just paid the cost of someone else''s bad manners. Their distraction is not a comment on you, it is a comment on them, on the event, or on their own bad day. Leaving quickly turns their small rudeness into your loss. Not taking things personally is a muscle. This was a chance to train it.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are three sentences into introducing your work when the person you are speaking with looks over your shoulder, half-waves at someone more senior, and says distractedly: ''sorry, what did you say your name was again?'', and then immediately: ''is Sarah here yet?''. What do you do?') 
     AND option_text = 'You feel a flash of embarrassment, mumble your name again, and quickly find an excuse to step away. This person clearly is not interested in you.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), -10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are three sentences into introducing your work when the person you are speaking with looks over your shoulder, half-waves at someone more senior, and says distractedly: ''sorry, what did you say your name was again?'', and then immediately: ''is Sarah here yet?''. What do you do?') 
     AND option_text = 'You feel a flash of embarrassment, mumble your name again, and quickly find an excuse to step away. This person clearly is not interested in you.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), -15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are three sentences into introducing your work when the person you are speaking with looks over your shoulder, half-waves at someone more senior, and says distractedly: ''sorry, what did you say your name was again?'', and then immediately: ''is Sarah here yet?''. What do you do?') 
     AND option_text = 'You feel a flash of embarrassment, mumble your name again, and quickly find an excuse to step away. This person clearly is not interested in you.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), 0);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You are three sentences into introducing your work when the person you are speaking with looks over your shoulder, half-waves at someone more senior, and says distractedly: ''sorry, what did you say your name was again?'', and then immediately: ''is Sarah here yet?''. What do you do?' ORDER BY id DESC LIMIT 1), 'You smile, repeat your name once clearly, and say warmly: ''I''ll let you catch Sarah, it was nice to meet you briefly. If you''re open to it, I''d love to send you a short message after the event.''', 'This is very good. You did not perform hurt feelings, you did not chase her attention, and you did not disappear either. You reclaimed the exit on your own terms, kept the door open, and moved on. Almost no one handles this moment this cleanly. It signals real maturity.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are three sentences into introducing your work when the person you are speaking with looks over your shoulder, half-waves at someone more senior, and says distractedly: ''sorry, what did you say your name was again?'', and then immediately: ''is Sarah here yet?''. What do you do?') 
     AND option_text = 'You smile, repeat your name once clearly, and say warmly: ''I''ll let you catch Sarah, it was nice to meet you briefly. If you''re open to it, I''d love to send you a short message after the event.''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are three sentences into introducing your work when the person you are speaking with looks over your shoulder, half-waves at someone more senior, and says distractedly: ''sorry, what did you say your name was again?'', and then immediately: ''is Sarah here yet?''. What do you do?') 
     AND option_text = 'You smile, repeat your name once clearly, and say warmly: ''I''ll let you catch Sarah, it was nice to meet you briefly. If you''re open to it, I''d love to send you a short message after the event.''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), 20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are three sentences into introducing your work when the person you are speaking with looks over your shoulder, half-waves at someone more senior, and says distractedly: ''sorry, what did you say your name was again?'', and then immediately: ''is Sarah here yet?''. What do you do?') 
     AND option_text = 'You smile, repeat your name once clearly, and say warmly: ''I''ll let you catch Sarah, it was nice to meet you briefly. If you''re open to it, I''d love to send you a short message after the event.''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), 15);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You are three sentences into introducing your work when the person you are speaking with looks over your shoulder, half-waves at someone more senior, and says distractedly: ''sorry, what did you say your name was again?'', and then immediately: ''is Sarah here yet?''. What do you do?' ORDER BY id DESC LIMIT 1), 'You raise your voice slightly and say: ''Excuse me, I was talking. Could you at least listen before you look for someone more important?''', 'The feeling behind this is valid, but the delivery costs more than it gains. You will be remembered as ''difficult'' rather than as someone worth taking seriously. Assertiveness is not the same as counter-rudeness. The stronger move is composure plus a clean exit, as in option 2.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are three sentences into introducing your work when the person you are speaking with looks over your shoulder, half-waves at someone more senior, and says distractedly: ''sorry, what did you say your name was again?'', and then immediately: ''is Sarah here yet?''. What do you do?') 
     AND option_text = 'You raise your voice slightly and say: ''Excuse me, I was talking. Could you at least listen before you look for someone more important?''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), 5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are three sentences into introducing your work when the person you are speaking with looks over your shoulder, half-waves at someone more senior, and says distractedly: ''sorry, what did you say your name was again?'', and then immediately: ''is Sarah here yet?''. What do you do?') 
     AND option_text = 'You raise your voice slightly and say: ''Excuse me, I was talking. Could you at least listen before you look for someone more important?''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), -20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are three sentences into introducing your work when the person you are speaking with looks over your shoulder, half-waves at someone more senior, and says distractedly: ''sorry, what did you say your name was again?'', and then immediately: ''is Sarah here yet?''. What do you do?') 
     AND option_text = 'You raise your voice slightly and say: ''Excuse me, I was talking. Could you at least listen before you look for someone more important?''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), -15);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 3: The Dismissal' AND owner_id = (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind') LIMIT 1), 'mcq', 2, LAST_INSERT_ID());

-- ============================================
-- Card 4
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), 4, 'Phase 4: The Kind Exit', 'Leaving without being rude', 'A clean, warm exit is more respectful than an unclear stay. You are not rude for leaving, you are responsible for your own time.', 'Women are socialised to stay in conversations they want to leave, and to interpret leaving as rudeness. This scenario teaches the specific technique of the ''warm exit'', a short, honest sentence that ends the conversation without ending the relationship. It is one of the single most useful phrases in professional networking.');

-- Component 1 for Card 3
INSERT INTO component_text (content) VALUES ('You have been in one conversation for 25 minutes. The person is friendly, but they are monopolising your time telling you about their project. Two of the people you wanted to meet just walked in. You need to leave this conversation without being rude. What do you do?');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 4: The Kind Exit' AND owner_id = (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind') LIMIT 1), 'text', 1, LAST_INSERT_ID());

-- Component 2 for Card 3
INSERT INTO component_mcq (question) VALUES ('You have been in one conversation for 25 minutes. The person is friendly, but they are monopolising your time telling you about their project. Two of the people you wanted to meet just walked in. You need to leave this conversation without being rude. What do you do?');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You have been in one conversation for 25 minutes. The person is friendly, but they are monopolising your time telling you about their project. Two of the people you wanted to meet just walked in. You need to leave this conversation without being rude. What do you do?' ORDER BY id DESC LIMIT 1), 'You keep nodding politely, glance at your phone twice to signal you need to leave, and hope she takes the hint. After all, you don''t want to be rude.', 'Hint-dropping is a common trap, you feel polite but you are actually being unclear, which is a form of unkindness. You will end up feeling drained, resentful, and you will miss the people you actually wanted to meet. Kindness is not the same as agreeing to be captured. A clear warm exit is more respectful than a fake nod.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have been in one conversation for 25 minutes. The person is friendly, but they are monopolising your time telling you about their project. Two of the people you wanted to meet just walked in. You need to leave this conversation without being rude. What do you do?') 
     AND option_text = 'You keep nodding politely, glance at your phone twice to signal you need to leave, and hope she takes the hint. After all, you don''t want to be rude.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), -20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have been in one conversation for 25 minutes. The person is friendly, but they are monopolising your time telling you about their project. Two of the people you wanted to meet just walked in. You need to leave this conversation without being rude. What do you do?') 
     AND option_text = 'You keep nodding politely, glance at your phone twice to signal you need to leave, and hope she takes the hint. After all, you don''t want to be rude.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), -5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have been in one conversation for 25 minutes. The person is friendly, but they are monopolising your time telling you about their project. Two of the people you wanted to meet just walked in. You need to leave this conversation without being rude. What do you do?') 
     AND option_text = 'You keep nodding politely, glance at your phone twice to signal you need to leave, and hope she takes the hint. After all, you don''t want to be rude.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), -10);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You have been in one conversation for 25 minutes. The person is friendly, but they are monopolising your time telling you about their project. Two of the people you wanted to meet just walked in. You need to leave this conversation without being rude. What do you do?' ORDER BY id DESC LIMIT 1), 'You wait for a natural pause, smile, and say: ''This has been really interesting, I''d love to hear more later. I''m going to say hi to a few people before the room fills up. Can I find you on LinkedIn so we can stay in touch?''', 'Excellent. You did three things well: you acknowledged the conversation warmly, you left cleanly on your own terms, and you kept the relationship open. Almost no one at this event will exit a conversation this well. This is exactly what assertive kindness looks like.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have been in one conversation for 25 minutes. The person is friendly, but they are monopolising your time telling you about their project. Two of the people you wanted to meet just walked in. You need to leave this conversation without being rude. What do you do?') 
     AND option_text = 'You wait for a natural pause, smile, and say: ''This has been really interesting, I''d love to hear more later. I''m going to say hi to a few people before the room fills up. Can I find you on LinkedIn so we can stay in touch?''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), 20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have been in one conversation for 25 minutes. The person is friendly, but they are monopolising your time telling you about their project. Two of the people you wanted to meet just walked in. You need to leave this conversation without being rude. What do you do?') 
     AND option_text = 'You wait for a natural pause, smile, and say: ''This has been really interesting, I''d love to hear more later. I''m going to say hi to a few people before the room fills up. Can I find you on LinkedIn so we can stay in touch?''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have been in one conversation for 25 minutes. The person is friendly, but they are monopolising your time telling you about their project. Two of the people you wanted to meet just walked in. You need to leave this conversation without being rude. What do you do?') 
     AND option_text = 'You wait for a natural pause, smile, and say: ''This has been really interesting, I''d love to hear more later. I''m going to say hi to a few people before the room fills up. Can I find you on LinkedIn so we can stay in touch?''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), 20);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You have been in one conversation for 25 minutes. The person is friendly, but they are monopolising your time telling you about their project. Two of the people you wanted to meet just walked in. You need to leave this conversation without being rude. What do you do?' ORDER BY id DESC LIMIT 1), 'You invent a fake phone call: ''sorry, I have to take this,'' and walk away. It gets you out, and she won''t feel personally rejected.', 'The fake call works once. But it teaches you that you can only leave conversations by lying, which is a very expensive habit to build. It also usually shows, people can tell. The real skill is exiting cleanly and warmly, without a script that makes you feel small.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have been in one conversation for 25 minutes. The person is friendly, but they are monopolising your time telling you about their project. Two of the people you wanted to meet just walked in. You need to leave this conversation without being rude. What do you do?') 
     AND option_text = 'You invent a fake phone call: ''sorry, I have to take this,'' and walk away. It gets you out, and she won''t feel personally rejected.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), -5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have been in one conversation for 25 minutes. The person is friendly, but they are monopolising your time telling you about their project. Two of the people you wanted to meet just walked in. You need to leave this conversation without being rude. What do you do?') 
     AND option_text = 'You invent a fake phone call: ''sorry, I have to take this,'' and walk away. It gets you out, and she won''t feel personally rejected.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), -10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have been in one conversation for 25 minutes. The person is friendly, but they are monopolising your time telling you about their project. Two of the people you wanted to meet just walked in. You need to leave this conversation without being rude. What do you do?') 
     AND option_text = 'You invent a fake phone call: ''sorry, I have to take this,'' and walk away. It gets you out, and she won''t feel personally rejected.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), -5);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 4: The Kind Exit' AND owner_id = (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind') LIMIT 1), 'mcq', 2, LAST_INSERT_ID());

-- ============================================
-- Card 5
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), 5, 'Phase 5: The Message', 'Reaching out online', 'A specific, four-sentence message gets more replies than a long, generic one, every time. Warmth is measured in specifics, not in words.', 'Online outreach is where most networking attempts quietly fail, either because the message is too vague to reply to, or too long to read. This scenario teaches the four-sentence structure that combines assertiveness (a clear ask) with warmth (specific, honest, respectful of her time).');

-- Component 1 for Card 4
INSERT INTO component_text (content) VALUES ('Two days after the event, you want to write to the senior director from Card 2. You had a great 10-minute conversation with her about a project she''s leading. You would love a 20-minute call to ask her advice about a similar challenge you''re facing. How do you write the message?');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 5: The Message' AND owner_id = (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind') LIMIT 1), 'text', 1, LAST_INSERT_ID());

-- Component 2 for Card 4
INSERT INTO component_mcq (question) VALUES ('Two days after the event, you want to write to the senior director from Card 2. You had a great 10-minute conversation with her about a project she''s leading. You would love a 20-minute call to ask her advice about a similar challenge you''re facing. How do you write the message?');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'Two days after the event, you want to write to the senior director from Card 2. You had a great 10-minute conversation with her about a project she''s leading. You would love a 20-minute call to ask her advice about a similar challenge you''re facing. How do you write the message?' ORDER BY id DESC LIMIT 1), 'You write a warm 4-sentence message: one specific line about your conversation, one honest sentence about why you''re writing, one clear small ask (a 20-minute call), and a graceful exit (''totally fine if it''s not a good moment'').', 'This is exactly the structure that gets replies. Specific, honest, small, respectful. You will be in the small minority of people whose messages actually land, and even if she says no, she will remember you well. This is strategic warmth in action.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'Two days after the event, you want to write to the senior director from Card 2. You had a great 10-minute conversation with her about a project she''s leading. You would love a 20-minute call to ask her advice about a similar challenge you''re facing. How do you write the message?') 
     AND option_text = 'You write a warm 4-sentence message: one specific line about your conversation, one honest sentence about why you''re writing, one clear small ask (a 20-minute call), and a graceful exit (''totally fine if it''s not a good moment'').' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), 20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'Two days after the event, you want to write to the senior director from Card 2. You had a great 10-minute conversation with her about a project she''s leading. You would love a 20-minute call to ask her advice about a similar challenge you''re facing. How do you write the message?') 
     AND option_text = 'You write a warm 4-sentence message: one specific line about your conversation, one honest sentence about why you''re writing, one clear small ask (a 20-minute call), and a graceful exit (''totally fine if it''s not a good moment'').' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), 10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'Two days after the event, you want to write to the senior director from Card 2. You had a great 10-minute conversation with her about a project she''s leading. You would love a 20-minute call to ask her advice about a similar challenge you''re facing. How do you write the message?') 
     AND option_text = 'You write a warm 4-sentence message: one specific line about your conversation, one honest sentence about why you''re writing, one clear small ask (a 20-minute call), and a graceful exit (''totally fine if it''s not a good moment'').' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), 20);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'Two days after the event, you want to write to the senior director from Card 2. You had a great 10-minute conversation with her about a project she''s leading. You would love a 20-minute call to ask her advice about a similar challenge you''re facing. How do you write the message?' ORDER BY id DESC LIMIT 1), 'You send: ''Hi! Great to meet you last week. Would love to pick your brain sometime. Let me know when works for you!''', 'This lands softly. ''Pick your brain'' is a phrase busy senior people quietly dread, it signals you haven''t thought about what you actually need. ''Sometime'' is not a real ask. And ''let me know when works for you'' hands her the entire logistical burden. She likes you, but she probably will not reply. Specificity is warmth.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'Two days after the event, you want to write to the senior director from Card 2. You had a great 10-minute conversation with her about a project she''s leading. You would love a 20-minute call to ask her advice about a similar challenge you''re facing. How do you write the message?') 
     AND option_text = 'You send: ''Hi! Great to meet you last week. Would love to pick your brain sometime. Let me know when works for you!''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), -5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'Two days after the event, you want to write to the senior director from Card 2. You had a great 10-minute conversation with her about a project she''s leading. You would love a 20-minute call to ask her advice about a similar challenge you''re facing. How do you write the message?') 
     AND option_text = 'You send: ''Hi! Great to meet you last week. Would love to pick your brain sometime. Let me know when works for you!''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), 0);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'Two days after the event, you want to write to the senior director from Card 2. You had a great 10-minute conversation with her about a project she''s leading. You would love a 20-minute call to ask her advice about a similar challenge you''re facing. How do you write the message?') 
     AND option_text = 'You send: ''Hi! Great to meet you last week. Would love to pick your brain sometime. Let me know when works for you!''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), -10);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'Two days after the event, you want to write to the senior director from Card 2. You had a great 10-minute conversation with her about a project she''s leading. You would love a 20-minute call to ask her advice about a similar challenge you''re facing. How do you write the message?' ORDER BY id DESC LIMIT 1), 'You write a 3-paragraph message explaining your background, your career goals, your current challenge in detail, and asking for her advice on all of it, plus an introduction to two people she knows.', 'The care behind this is visible, but the length works against you. Senior women receive many long messages every week and rarely have time to read them, let alone respond. The short, specific message with one small ask outperforms the long detailed one every time. Less is not just faster, it is more respectful.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'Two days after the event, you want to write to the senior director from Card 2. You had a great 10-minute conversation with her about a project she''s leading. You would love a 20-minute call to ask her advice about a similar challenge you''re facing. How do you write the message?') 
     AND option_text = 'You write a 3-paragraph message explaining your background, your career goals, your current challenge in detail, and asking for her advice on all of it, plus an introduction to two people she knows.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), 10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'Two days after the event, you want to write to the senior director from Card 2. You had a great 10-minute conversation with her about a project she''s leading. You would love a 20-minute call to ask her advice about a similar challenge you''re facing. How do you write the message?') 
     AND option_text = 'You write a 3-paragraph message explaining your background, your career goals, your current challenge in detail, and asking for her advice on all of it, plus an introduction to two people she knows.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), -5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'Two days after the event, you want to write to the senior director from Card 2. You had a great 10-minute conversation with her about a project she''s leading. You would love a 20-minute call to ask her advice about a similar challenge you''re facing. How do you write the message?') 
     AND option_text = 'You write a 3-paragraph message explaining your background, your career goals, your current challenge in detail, and asking for her advice on all of it, plus an introduction to two people she knows.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), -10);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 5: The Message' AND owner_id = (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind') LIMIT 1), 'mcq', 2, LAST_INSERT_ID());

-- ============================================
-- Card 6
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), 6, 'Phase 6: The Follow-Up', 'Bridging the gap', 'The follow-up is the relationship. The first conversation is just the beginning. Cleverness is not required. Being on time is.', 'This final scenario tests the moment where most networking attempts quietly die: the unfollowed-up conversation. It teaches that follow-ups are judged on timeliness and specificity, not on cleverness or eloquence, and that over-apologising is its own form of self-diminishment.');

-- Component 1 for Card 5
INSERT INTO component_text (content) VALUES ('It has now been 5 days since a great coffee with someone you really connected with. You keep meaning to send a follow-up message, and you keep not doing it. The longer you wait, the more awkward it feels. What do you do?');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 6: The Follow-Up' AND owner_id = (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind') LIMIT 1), 'text', 1, LAST_INSERT_ID());

-- Component 2 for Card 5
INSERT INTO component_mcq (question) VALUES ('It has now been 5 days since a great coffee with someone you really connected with. You keep meaning to send a follow-up message, and you keep not doing it. The longer you wait, the more awkward it feels. What do you do?');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'It has now been 5 days since a great coffee with someone you really connected with. You keep meaning to send a follow-up message, and you keep not doing it. The longer you wait, the more awkward it feels. What do you do?' ORDER BY id DESC LIMIT 1), 'You keep waiting until you have ''something clever'' to say. You''ll send it when the right words come. Better late and perfect than early and average.', 'This is one of the most common self-sabotages in networking. ''Waiting for the right words'' is almost always waiting for the anxiety to disappear, and it will not disappear. Meanwhile, the memory of your conversation fades on her side. Follow-ups are not judged on cleverness. They are judged on warmth and timeliness. Cleverness is a trap.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It has now been 5 days since a great coffee with someone you really connected with. You keep meaning to send a follow-up message, and you keep not doing it. The longer you wait, the more awkward it feels. What do you do?') 
     AND option_text = 'You keep waiting until you have ''something clever'' to say. You''ll send it when the right words come. Better late and perfect than early and average.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), -15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It has now been 5 days since a great coffee with someone you really connected with. You keep meaning to send a follow-up message, and you keep not doing it. The longer you wait, the more awkward it feels. What do you do?') 
     AND option_text = 'You keep waiting until you have ''something clever'' to say. You''ll send it when the right words come. Better late and perfect than early and average.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), -10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It has now been 5 days since a great coffee with someone you really connected with. You keep meaning to send a follow-up message, and you keep not doing it. The longer you wait, the more awkward it feels. What do you do?') 
     AND option_text = 'You keep waiting until you have ''something clever'' to say. You''ll send it when the right words come. Better late and perfect than early and average.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), -15);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'It has now been 5 days since a great coffee with someone you really connected with. You keep meaning to send a follow-up message, and you keep not doing it. The longer you wait, the more awkward it feels. What do you do?' ORDER BY id DESC LIMIT 1), 'You send a 3-sentence message today: ''Really enjoyed our conversation last week, I thought more about what you said about X and it made me realise Y. No need to reply, just wanted to say thank you.''', 'This is textbook. Warm, specific, short, no obligation. You just placed yourself in the small minority of people who actually follow up, which, statistically, is the single biggest differentiator between women who build strong networks and those who don''t. Well done.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It has now been 5 days since a great coffee with someone you really connected with. You keep meaning to send a follow-up message, and you keep not doing it. The longer you wait, the more awkward it feels. What do you do?') 
     AND option_text = 'You send a 3-sentence message today: ''Really enjoyed our conversation last week, I thought more about what you said about X and it made me realise Y. No need to reply, just wanted to say thank you.''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), 20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It has now been 5 days since a great coffee with someone you really connected with. You keep meaning to send a follow-up message, and you keep not doing it. The longer you wait, the more awkward it feels. What do you do?') 
     AND option_text = 'You send a 3-sentence message today: ''Really enjoyed our conversation last week, I thought more about what you said about X and it made me realise Y. No need to reply, just wanted to say thank you.''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It has now been 5 days since a great coffee with someone you really connected with. You keep meaning to send a follow-up message, and you keep not doing it. The longer you wait, the more awkward it feels. What do you do?') 
     AND option_text = 'You send a 3-sentence message today: ''Really enjoyed our conversation last week, I thought more about what you said about X and it made me realise Y. No need to reply, just wanted to say thank you.''' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), 20);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'It has now been 5 days since a great coffee with someone you really connected with. You keep meaning to send a follow-up message, and you keep not doing it. The longer you wait, the more awkward it feels. What do you do?' ORDER BY id DESC LIMIT 1), 'You send a long apology message: ''I''m so sorry I didn''t get back to you sooner, this week has been so crazy, I hope you don''t think I''m rude, I really did enjoy our conversation and I meant to write earlier but…'' and go on to explain the delay in detail.', 'The instinct to apologise is understandable, but a long apology draws more attention to a gap she probably didn''t notice. It also puts you in a lower-status position from the start of the message, and forces her to reassure you. A clean three-sentence message with no apology outperforms a long apologetic one, almost every time.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It has now been 5 days since a great coffee with someone you really connected with. You keep meaning to send a follow-up message, and you keep not doing it. The longer you wait, the more awkward it feels. What do you do?') 
     AND option_text = 'You send a long apology message: ''I''m so sorry I didn''t get back to you sooner, this week has been so crazy, I hope you don''t think I''m rude, I really did enjoy our conversation and I meant to write earlier but…'' and go on to explain the delay in detail.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), -5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It has now been 5 days since a great coffee with someone you really connected with. You keep meaning to send a follow-up message, and you keep not doing it. The longer you wait, the more awkward it feels. What do you do?') 
     AND option_text = 'You send a long apology message: ''I''m so sorry I didn''t get back to you sooner, this week has been so crazy, I hope you don''t think I''m rude, I really did enjoy our conversation and I meant to write earlier but…'' and go on to explain the delay in detail.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), -10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'It has now been 5 days since a great coffee with someone you really connected with. You keep meaning to send a follow-up message, and you keep not doing it. The longer you wait, the more awkward it feels. What do you do?') 
     AND option_text = 'You send a long apology message: ''I''m so sorry I didn''t get back to you sooner, this week has been so crazy, I hope you don''t think I''m rude, I really did enjoy our conversation and I meant to write earlier but…'' and go on to explain the delay in detail.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), -5);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 6: The Follow-Up' AND owner_id = (SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind') LIMIT 1), 'mcq', 2, LAST_INSERT_ID());

-- ============================================
-- Feedback Tiers
-- ============================================

-- Feedback for metric 'Assertiveness' (Score 0-49)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), 0, 49, 'You are considerate and careful with people, you rarely make anyone feel small.', 'You hesitate to open conversations, exit them, or ask for what you want. Politeness can quietly cost you the connections you were hoping to build.', 'Before your next event, write down one short opener you can actually say out loud. Practise it once in the mirror. That is enough.', NULL, 'When assertiveness is low, the most valuable step is reducing the friction of the first sentence. The Networking course walks you through the three-question prep, honest openers, and the warm exit, the exact scripts that make it easier to speak up without feeling aggressive or rehearsed.');

-- Feedback for metric 'Assertiveness' (Score 50-85)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), 50, 85, 'You can ask for what you need and hold your ground when the situation calls for it.', 'You still hesitate in higher-stakes moments, with senior people, in group settings, or when you feel dismissed.', 'Pick one situation this week where you would normally stay quiet and say the honest, warm version instead. One sentence is enough.', NULL, 'You have a working level of assertiveness, the next step is making it reliable under pressure. The Networking course gives you the scripts and mindset for the harder moments: dismissive audiences, monopolising conversations, and the follow-up messages you have been postponing.');

-- Feedback for metric 'Assertiveness' (Score 85-100)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_metric WHERE name = 'Assertiveness' LIMIT 1), 85, 100, 'You ask clearly, exit cleanly, and hold your ground with warmth. Your presence is felt.', 'None. Watch that assertiveness stays paired with genuine curiosity about others, the combination is what makes it landing rather than intimidating.', 'Mentor a woman in your circle who struggles to speak up. Teach her one script that changed things for you.', NULL, 'Confident assertiveness becomes most powerful when it is paired with genuine curiosity and generosity. The Networking course helps you keep your directness in service of relationship quality, so your clarity opens doors instead of closing them, and you actively lift the less-confident women in the room around you.');

-- Feedback for metric 'Composure' (Score 0-49)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), 0, 49, 'You are emotionally attuned, you notice when someone is distracted, tired, or off. That sensitivity is a real strength.', 'You often take other people''s bad moments personally. A distracted look or a short reply can linger for hours or days and quietly discourage you from reaching out again.', 'The next time someone is distracted in a conversation with you, silently repeat: ''that is information about their day, not about me.'' Then continue as normal.', NULL, 'When composure is low, small social frictions carry outsized weight, and that weight is one of the main reasons women pull back from networking. The Networking course teaches you how to read a dismissive moment as data about the other person, not as evidence about your own worth, so you keep showing up.');

-- Feedback for metric 'Composure' (Score 50-85)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), 50, 85, 'You recover well from small social frictions and stay open to reconnecting.', 'You still take some interactions personally, usually with senior people, or in moments where you felt you did not perform at your best.', 'After a conversation that felt off, ask yourself: ''what is one non-personal reason this might have gone the way it did?'', before your inner critic gets there first.', NULL, 'You already have a working composure, the next step is protecting it in higher-stakes moments. The Networking course helps you build a repeatable inner script for handling dismissive or distracted people, so you leave events remembering the connections you made, not the small stumbles.');

-- Feedback for metric 'Composure' (Score 85-100)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_metric WHERE name = 'Composure' LIMIT 1), 85, 100, 'You handle rudeness, distraction, and awkward moments without letting them define you.', 'None. Just watch that composure does not tip into detachment, you still want to be reachable, not armoured.', 'Notice one moment this week where composure served you. Name it clearly to yourself, that is the reference point you want to build on.', NULL, 'Strong composure is one of the most valuable networking assets, because it lets you keep showing up when others quietly retreat. The Networking course helps you channel that composure into strategic follow-up habits, so the calm you already have translates into connections that actually mature over time.');

-- Feedback for metric 'Strategic warmth' (Score 0-49)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), 0, 49, 'You are honest and unpretentious. People sense they are dealing with a real person, not a performance.', 'You either go too transactional (''what can I get from this person?'') or too diffuse (''everyone is lovely, but nothing follows''). You leave events without a clear next step.', 'Before your next networking moment, write down one specific thing you can offer to someone, an intro, a resource, a compliment on real work. One is enough.', NULL, 'When strategic warmth is low, networking often collapses into either awkward transaction or pleasant vagueness. The Networking course teaches you how to combine specificity with generosity, the openers, four-sentence messages, and 48-hour follow-ups that turn casual conversations into real relationships.');

-- Feedback for metric 'Strategic warmth' (Score 50-85)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), 50, 85, 'You know how to be warm and specific at the same time. People remember conversations with you.', 'You sometimes hesitate to make a clear ask, or you follow up warmly without proposing a next step. Warmth needs a container to move relationships forward.', 'In your next follow-up message, add one specific, small ask or offer, a 20-minute call, an introduction, a resource you could share. Warmth plus a container.', NULL, 'You have the harder half of strategic warmth already, genuine care and specific attention. The Networking course helps you add the missing piece: the small, honest, clear ask or offer that turns warm moments into concrete relationships. This is where good networkers become excellent ones.');

-- Feedback for metric 'Strategic warmth' (Score 85-100)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Networking with Nerve: Assertive, Composed, Strategic, Kind'), (SELECT id FROM simulator_metric WHERE name = 'Strategic warmth' LIMIT 1), 85, 100, 'You combine genuine warmth with strategic clarity. People feel seen by you and also know exactly what you''re asking for.', 'None. Just make sure you are letting the warmth flow both ways, accept help and connection as freely as you offer them.', 'Reach out to one person in your network this week with no ask at all, only a thank-you or a piece of information they would find useful. Warmth without transaction.', NULL, 'Strategic warmth at this level is a rare and valuable capacity, it is what lets you build a network of people who both trust you and know how to help you. The Networking course helps you deepen that further, especially in the long-term maintenance of relationships: how to stay meaningfully present in people''s lives without turning every touch into a transaction.');

-- ============================================
-- End of generated queries
-- ============================================
