-- ============================================
-- SQL Queries Generated on 2026-08-23 19:54:10.809561
-- ============================================
-- These queries can be copied and executed directly
-- Subqueries are used to automatically resolve IDs
-- ============================================


-- ============================================
-- Simulator: Self-Care for Strong Leaders
-- ============================================
INSERT INTO simulator (title, description, level, localisation, estimated_duration, created_at) VALUES ('Self-Care for Strong Leaders', 'No description', 'core', 'Work / Home / Community', 15, '2026-08-23 19:54:10.808786');

-- Simulator Tags
INSERT INTO simulator_tag (name) VALUES ('Self-Care');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_tag WHERE name = 'Self-Care' LIMIT 1));
INSERT INTO simulator_tag (name) VALUES ('Leadership');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_tag WHERE name = 'Leadership' LIMIT 1));
INSERT INTO simulator_tag (name) VALUES ('Resilience');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_tag WHERE name = 'Resilience' LIMIT 1));
INSERT INTO simulator_tag (name) VALUES ('Confidence');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_tag WHERE name = 'Confidence' LIMIT 1));
INSERT INTO simulator_tag (name) VALUES ('Boundaries');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_tag WHERE name = 'Boundaries' LIMIT 1));
INSERT INTO simulator_tag (name) VALUES ('Women''s Leadership');
INSERT INTO simulator_contains_tag (simulator_id, simulator_tag_id) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_tag WHERE name = 'Women''s Leadership' LIMIT 1));

-- Simulator Metrics
INSERT INTO simulator_metric (name) VALUES ('Energy Management');
INSERT INTO simulator_contains_metric (simulator_id, metric_id) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1));
INSERT INTO simulator_metric (name) VALUES ('Boundaries');
INSERT INTO simulator_contains_metric (simulator_id, metric_id) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1));
INSERT INTO simulator_metric (name) VALUES ('Self-Compassion');
INSERT INTO simulator_contains_metric (simulator_id, metric_id) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1));

-- ============================================
-- Card 1
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), 1, 'Phase 1: The Signal', 'When your body speaks before you do', 'Your body is not your enemy. It is your earliest and most honest leadership advisor. Listening to it is the first act of sustainable leadership.', 'This opening scenario introduces the central theme: self-care as leadership intelligence, not indulgence. It helps learners recognise the physical and emotional signals of depletion before they reach crisis point — and practise making a deliberate choice in response.');

-- Component 1 for Card 0
INSERT INTO component_image (image_url, image_alt, image_description) VALUES ('https://unsplash.com/photos/tired-person-resting-head-on-hand-at-desk-r4DfnsCINp4', NULL, NULL);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 1: The Signal' AND owner_id = (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders') LIMIT 1), 'image', 1, LAST_INSERT_ID());

-- Component 2 for Card 0
INSERT INTO component_text (content) VALUES ('You are in the middle of an intense work week. You have delivered on every deadline, supported your team, and attended every meeting. But now, on Thursday evening, you feel completely flat — no energy left, difficulty concentrating, and a creeping irritability you cannot explain. Your calendar tomorrow is already full.');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 1: The Signal' AND owner_id = (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders') LIMIT 1), 'text', 2, LAST_INSERT_ID());

-- Component 3 for Card 0
INSERT INTO component_mcq (question) VALUES ('You are in the middle of an intense work week. You have delivered on every deadline, supported your team, and attended every meeting. But now, on Thursday evening, you feel completely flat — no energy left, difficulty concentrating, and a creeping irritability you cannot explain. Your calendar tomorrow is already full.');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You are in the middle of an intense work week. You have delivered on every deadline, supported your team, and attended every meeting. But now, on Thursday evening, you feel completely flat — no energy left, difficulty concentrating, and a creeping irritability you cannot explain. Your calendar tomorrow is already full.' ORDER BY id DESC LIMIT 1), 'You push through — there is too much at stake to slow down now.', 'This is a very common response, especially for leaders who feel responsible for everything. But ignoring the signal does not make it disappear — it compounds it. Fatigue that is not addressed becomes burnout. Strength begins with noticing, not ignoring.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are in the middle of an intense work week. You have delivered on every deadline, supported your team, and attended every meeting. But now, on Thursday evening, you feel completely flat — no energy left, difficulty concentrating, and a creeping irritability you cannot explain. Your calendar tomorrow is already full.') 
     AND option_text = 'You push through — there is too much at stake to slow down now.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), -15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are in the middle of an intense work week. You have delivered on every deadline, supported your team, and attended every meeting. But now, on Thursday evening, you feel completely flat — no energy left, difficulty concentrating, and a creeping irritability you cannot explain. Your calendar tomorrow is already full.') 
     AND option_text = 'You push through — there is too much at stake to slow down now.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), -10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are in the middle of an intense work week. You have delivered on every deadline, supported your team, and attended every meeting. But now, on Thursday evening, you feel completely flat — no energy left, difficulty concentrating, and a creeping irritability you cannot explain. Your calendar tomorrow is already full.') 
     AND option_text = 'You push through — there is too much at stake to slow down now.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), -10);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You are in the middle of an intense work week. You have delivered on every deadline, supported your team, and attended every meeting. But now, on Thursday evening, you feel completely flat — no energy left, difficulty concentrating, and a creeping irritability you cannot explain. Your calendar tomorrow is already full.' ORDER BY id DESC LIMIT 1), 'You cancel everything non-essential for tomorrow morning and protect that time for yourself.', 'Strong choice. Recognising when to pause is a leadership skill, not a weakness. Protecting recovery time — even imperfectly — signals to yourself and others that your energy matters. Leaders who recharge make better decisions.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are in the middle of an intense work week. You have delivered on every deadline, supported your team, and attended every meeting. But now, on Thursday evening, you feel completely flat — no energy left, difficulty concentrating, and a creeping irritability you cannot explain. Your calendar tomorrow is already full.') 
     AND option_text = 'You cancel everything non-essential for tomorrow morning and protect that time for yourself.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are in the middle of an intense work week. You have delivered on every deadline, supported your team, and attended every meeting. But now, on Thursday evening, you feel completely flat — no energy left, difficulty concentrating, and a creeping irritability you cannot explain. Your calendar tomorrow is already full.') 
     AND option_text = 'You cancel everything non-essential for tomorrow morning and protect that time for yourself.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are in the middle of an intense work week. You have delivered on every deadline, supported your team, and attended every meeting. But now, on Thursday evening, you feel completely flat — no energy left, difficulty concentrating, and a creeping irritability you cannot explain. Your calendar tomorrow is already full.') 
     AND option_text = 'You cancel everything non-essential for tomorrow morning and protect that time for yourself.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), 15);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You are in the middle of an intense work week. You have delivered on every deadline, supported your team, and attended every meeting. But now, on Thursday evening, you feel completely flat — no energy left, difficulty concentrating, and a creeping irritability you cannot explain. Your calendar tomorrow is already full.' ORDER BY id DESC LIMIT 1), 'You tell yourself you will rest at the weekend and keep going for now.', 'Deferring recovery is a common coping strategy, but "the weekend" rarely arrives with the restoration we promise ourselves. Self-care is most effective as a daily practice, not a reward at the finish line.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are in the middle of an intense work week. You have delivered on every deadline, supported your team, and attended every meeting. But now, on Thursday evening, you feel completely flat — no energy left, difficulty concentrating, and a creeping irritability you cannot explain. Your calendar tomorrow is already full.') 
     AND option_text = 'You tell yourself you will rest at the weekend and keep going for now.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), -5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are in the middle of an intense work week. You have delivered on every deadline, supported your team, and attended every meeting. But now, on Thursday evening, you feel completely flat — no energy left, difficulty concentrating, and a creeping irritability you cannot explain. Your calendar tomorrow is already full.') 
     AND option_text = 'You tell yourself you will rest at the weekend and keep going for now.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), -5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are in the middle of an intense work week. You have delivered on every deadline, supported your team, and attended every meeting. But now, on Thursday evening, you feel completely flat — no energy left, difficulty concentrating, and a creeping irritability you cannot explain. Your calendar tomorrow is already full.') 
     AND option_text = 'You tell yourself you will rest at the weekend and keep going for now.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), -5);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 1: The Signal' AND owner_id = (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders') LIMIT 1), 'mcq', 3, LAST_INSERT_ID());

-- ============================================
-- Card 2
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), 2, 'Phase 2: The Ask', 'When taking care of yourself feels selfish', 'Choosing yourself is not abandoning others. It is making sure that when you show up, you are truly present — not depleted and resentful.', 'This scenario explores the most common internal barrier to self-care: the belief that prioritising yourself is selfish or unhelpful. It helps learners practise saying a clear, caring no — and recognise that a well-placed boundary protects the quality of their contribution, not just their comfort.');

-- Component 1 for Card 1
INSERT INTO component_image (image_url, image_alt, image_description) VALUES ('https://unsplash.com/photos/silhouette-of-personr-TzVN0xQhWaQ', NULL, NULL);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 2: The Ask' AND owner_id = (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders') LIMIT 1), 'image', 1, LAST_INSERT_ID());

-- Component 2 for Card 1
INSERT INTO component_text (content) VALUES ('A colleague asks for your help with a task you are not responsible for. You like this person, and the task is genuinely important. But you are already stretched, and this would cost you the one hour you had mentally reserved to recover. You feel the familiar pull: say yes, because that is what reliable people do.');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 2: The Ask' AND owner_id = (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders') LIMIT 1), 'text', 2, LAST_INSERT_ID());

-- Component 3 for Card 1
INSERT INTO component_mcq (question) VALUES ('A colleague asks for your help with a task you are not responsible for. You like this person, and the task is genuinely important. But you are already stretched, and this would cost you the one hour you had mentally reserved to recover. You feel the familiar pull: say yes, because that is what reliable people do.');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'A colleague asks for your help with a task you are not responsible for. You like this person, and the task is genuinely important. But you are already stretched, and this would cost you the one hour you had mentally reserved to recover. You feel the familiar pull: say yes, because that is what reliable people do.' ORDER BY id DESC LIMIT 1), 'You agree to help, telling yourself you can rest later.', 'Helpfulness is a genuine strength — but when it consistently overrides your own needs, it becomes a pattern that is difficult to break. Others learn to rely on your unlimited availability, and your own recovery becomes invisible.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague asks for your help with a task you are not responsible for. You like this person, and the task is genuinely important. But you are already stretched, and this would cost you the one hour you had mentally reserved to recover. You feel the familiar pull: say yes, because that is what reliable people do.') 
     AND option_text = 'You agree to help, telling yourself you can rest later.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), -10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague asks for your help with a task you are not responsible for. You like this person, and the task is genuinely important. But you are already stretched, and this would cost you the one hour you had mentally reserved to recover. You feel the familiar pull: say yes, because that is what reliable people do.') 
     AND option_text = 'You agree to help, telling yourself you can rest later.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), -15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague asks for your help with a task you are not responsible for. You like this person, and the task is genuinely important. But you are already stretched, and this would cost you the one hour you had mentally reserved to recover. You feel the familiar pull: say yes, because that is what reliable people do.') 
     AND option_text = 'You agree to help, telling yourself you can rest later.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), -10);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'A colleague asks for your help with a task you are not responsible for. You like this person, and the task is genuinely important. But you are already stretched, and this would cost you the one hour you had mentally reserved to recover. You feel the familiar pull: say yes, because that is what reliable people do.' ORDER BY id DESC LIMIT 1), 'You say: "I want to help, but I cannot take this on today. Can we find another solution together?"', 'Excellent. This response is honest, respectful, and constructive. It protects your energy without abandoning your colleague. Offering to think through alternatives together shows leadership — you are contributing without carrying.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague asks for your help with a task you are not responsible for. You like this person, and the task is genuinely important. But you are already stretched, and this would cost you the one hour you had mentally reserved to recover. You feel the familiar pull: say yes, because that is what reliable people do.') 
     AND option_text = 'You say: "I want to help, but I cannot take this on today. Can we find another solution together?"' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague asks for your help with a task you are not responsible for. You like this person, and the task is genuinely important. But you are already stretched, and this would cost you the one hour you had mentally reserved to recover. You feel the familiar pull: say yes, because that is what reliable people do.') 
     AND option_text = 'You say: "I want to help, but I cannot take this on today. Can we find another solution together?"' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), 20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague asks for your help with a task you are not responsible for. You like this person, and the task is genuinely important. But you are already stretched, and this would cost you the one hour you had mentally reserved to recover. You feel the familiar pull: say yes, because that is what reliable people do.') 
     AND option_text = 'You say: "I want to help, but I cannot take this on today. Can we find another solution together?"' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), 15);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'A colleague asks for your help with a task you are not responsible for. You like this person, and the task is genuinely important. But you are already stretched, and this would cost you the one hour you had mentally reserved to recover. You feel the familiar pull: say yes, because that is what reliable people do.' ORDER BY id DESC LIMIT 1), 'You say yes but feel resentful, telling yourself you have no real choice.', 'The feeling of having no choice is worth examining. In most cases, a choice does exist — it is simply uncomfortable. Resentment is a signal that a boundary has been crossed. Noticing it is already progress.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague asks for your help with a task you are not responsible for. You like this person, and the task is genuinely important. But you are already stretched, and this would cost you the one hour you had mentally reserved to recover. You feel the familiar pull: say yes, because that is what reliable people do.') 
     AND option_text = 'You say yes but feel resentful, telling yourself you have no real choice.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), -10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague asks for your help with a task you are not responsible for. You like this person, and the task is genuinely important. But you are already stretched, and this would cost you the one hour you had mentally reserved to recover. You feel the familiar pull: say yes, because that is what reliable people do.') 
     AND option_text = 'You say yes but feel resentful, telling yourself you have no real choice.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), -15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'A colleague asks for your help with a task you are not responsible for. You like this person, and the task is genuinely important. But you are already stretched, and this would cost you the one hour you had mentally reserved to recover. You feel the familiar pull: say yes, because that is what reliable people do.') 
     AND option_text = 'You say yes but feel resentful, telling yourself you have no real choice.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), -5);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 2: The Ask' AND owner_id = (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders') LIMIT 1), 'mcq', 3, LAST_INSERT_ID());

-- ============================================
-- Card 3
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), 3, 'Phase 3: The Habit', 'Building something that actually lasts', 'The best self-care habit is not the most beautiful one. It is the one you will actually do — on Tuesday morning, when you are tired, before your day takes over.', 'This scenario addresses the gap between intention and habit — one of the most common failure points in self-care. It helps learners apply the principle of consistency over perfection, and design a practice that fits their actual life rather than an aspirational one.');

-- Component 1 for Card 2
INSERT INTO component_image (image_url, image_alt, image_description) VALUES ('https://unsplash.com/photos/woman-meditating-on-floor-with-overlooking-view-of-trees-8w7b4SdhOgw', NULL, NULL);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 3: The Habit' AND owner_id = (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders') LIMIT 1), 'image', 1, LAST_INSERT_ID());

-- Component 2 for Card 2
INSERT INTO component_text (content) VALUES ('You have decided to start a self-care practice. You want it to be consistent and realistic. You know from experience that big intentions often fade after a few days. You are thinking about what approach would actually work for your life — not the ideal version of your life, but the real one, this week.');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 3: The Habit' AND owner_id = (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders') LIMIT 1), 'text', 2, LAST_INSERT_ID());

-- Component 3 for Card 2
INSERT INTO component_mcq (question) VALUES ('You have decided to start a self-care practice. You want it to be consistent and realistic. You know from experience that big intentions often fade after a few days. You are thinking about what approach would actually work for your life — not the ideal version of your life, but the real one, this week.');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You have decided to start a self-care practice. You want it to be consistent and realistic. You know from experience that big intentions often fade after a few days. You are thinking about what approach would actually work for your life — not the ideal version of your life, but the real one, this week.' ORDER BY id DESC LIMIT 1), 'You design an ambitious morning routine: exercise, journaling, meditation, and a healthy breakfast — every day.', 'Ambition in self-care is understandable — but complexity is the enemy of consistency. When one element fails, the whole routine collapses. Start with one anchor habit and build from there. Perfection is not the goal; repetition is.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have decided to start a self-care practice. You want it to be consistent and realistic. You know from experience that big intentions often fade after a few days. You are thinking about what approach would actually work for your life — not the ideal version of your life, but the real one, this week.') 
     AND option_text = 'You design an ambitious morning routine: exercise, journaling, meditation, and a healthy breakfast — every day.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), 5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have decided to start a self-care practice. You want it to be consistent and realistic. You know from experience that big intentions often fade after a few days. You are thinking about what approach would actually work for your life — not the ideal version of your life, but the real one, this week.') 
     AND option_text = 'You design an ambitious morning routine: exercise, journaling, meditation, and a healthy breakfast — every day.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), 5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have decided to start a self-care practice. You want it to be consistent and realistic. You know from experience that big intentions often fade after a few days. You are thinking about what approach would actually work for your life — not the ideal version of your life, but the real one, this week.') 
     AND option_text = 'You design an ambitious morning routine: exercise, journaling, meditation, and a healthy breakfast — every day.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), -10);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You have decided to start a self-care practice. You want it to be consistent and realistic. You know from experience that big intentions often fade after a few days. You are thinking about what approach would actually work for your life — not the ideal version of your life, but the real one, this week.' ORDER BY id DESC LIMIT 1), 'You choose one small, specific practice — three minutes of breathing before your first meeting — and commit to it for seven days.', 'This is exactly the right approach. A small, specific habit that fits your real schedule is far more powerful than a large one that depends on everything going perfectly. Consistency over seven days builds more momentum than perfection over two.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have decided to start a self-care practice. You want it to be consistent and realistic. You know from experience that big intentions often fade after a few days. You are thinking about what approach would actually work for your life — not the ideal version of your life, but the real one, this week.') 
     AND option_text = 'You choose one small, specific practice — three minutes of breathing before your first meeting — and commit to it for seven days.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), 20);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have decided to start a self-care practice. You want it to be consistent and realistic. You know from experience that big intentions often fade after a few days. You are thinking about what approach would actually work for your life — not the ideal version of your life, but the real one, this week.') 
     AND option_text = 'You choose one small, specific practice — three minutes of breathing before your first meeting — and commit to it for seven days.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), 10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have decided to start a self-care practice. You want it to be consistent and realistic. You know from experience that big intentions often fade after a few days. You are thinking about what approach would actually work for your life — not the ideal version of your life, but the real one, this week.') 
     AND option_text = 'You choose one small, specific practice — three minutes of breathing before your first meeting — and commit to it for seven days.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), 20);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You have decided to start a self-care practice. You want it to be consistent and realistic. You know from experience that big intentions often fade after a few days. You are thinking about what approach would actually work for your life — not the ideal version of your life, but the real one, this week.' ORDER BY id DESC LIMIT 1), 'You wait until you have a quieter week before starting — then it will feel more sustainable.', 'The quieter week rarely comes. And if it does, the habit built in easy conditions rarely survives the return of a busy one. The most resilient self-care practices are the ones designed for real, imperfect, demanding weeks — not ideal ones.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have decided to start a self-care practice. You want it to be consistent and realistic. You know from experience that big intentions often fade after a few days. You are thinking about what approach would actually work for your life — not the ideal version of your life, but the real one, this week.') 
     AND option_text = 'You wait until you have a quieter week before starting — then it will feel more sustainable.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), -5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have decided to start a self-care practice. You want it to be consistent and realistic. You know from experience that big intentions often fade after a few days. You are thinking about what approach would actually work for your life — not the ideal version of your life, but the real one, this week.') 
     AND option_text = 'You wait until you have a quieter week before starting — then it will feel more sustainable.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), 0);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You have decided to start a self-care practice. You want it to be consistent and realistic. You know from experience that big intentions often fade after a few days. You are thinking about what approach would actually work for your life — not the ideal version of your life, but the real one, this week.') 
     AND option_text = 'You wait until you have a quieter week before starting — then it will feel more sustainable.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), -5);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 3: The Habit' AND owner_id = (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders') LIMIT 1), 'mcq', 3, LAST_INSERT_ID());

-- ============================================
-- Card 4
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), 4, 'Phase 4: The Voice', 'What you say to yourself when no one is watching', 'Confidence grows where care begins — and that care starts with the voice inside your head. You deserve the same kindness you would offer anyone you lead.', 'This scenario introduces self-compassion as a core dimension of self-care. It helps learners recognise that how they speak to themselves directly affects their energy, confidence, and leadership capacity — and that inner kindness is a skill, not a personality trait.');

-- Component 1 for Card 3
INSERT INTO component_image (image_url, image_alt, image_description) VALUES ('https://unsplash.com/photos/woman-writing-in-notebook-with-pen-tcyW6Im5Uug', NULL, NULL);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 4: The Voice' AND owner_id = (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders') LIMIT 1), 'image', 1, LAST_INSERT_ID());

-- Component 2 for Card 3
INSERT INTO component_text (content) VALUES ('You made a mistake at work today — a small one, but visible. In the hours that follow, you notice the internal voice: the one that replays the moment, questions your competence, and compares you to others who seem to handle things more easily. You know this voice well. You are wondering how to respond to it.');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 4: The Voice' AND owner_id = (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders') LIMIT 1), 'text', 2, LAST_INSERT_ID());

-- Component 3 for Card 3
INSERT INTO component_mcq (question) VALUES ('You made a mistake at work today — a small one, but visible. In the hours that follow, you notice the internal voice: the one that replays the moment, questions your competence, and compares you to others who seem to handle things more easily. You know this voice well. You are wondering how to respond to it.');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You made a mistake at work today — a small one, but visible. In the hours that follow, you notice the internal voice: the one that replays the moment, questions your competence, and compares you to others who seem to handle things more easily. You know this voice well. You are wondering how to respond to it.' ORDER BY id DESC LIMIT 1), 'You let the inner critic run. It keeps you sharp and motivated to do better.', 'There is a difference between healthy reflection and self-criticism. One helps you learn; the other drains your energy and confidence without adding insight. A harsh inner voice does not make you better — it makes the next challenge harder to face.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You made a mistake at work today — a small one, but visible. In the hours that follow, you notice the internal voice: the one that replays the moment, questions your competence, and compares you to others who seem to handle things more easily. You know this voice well. You are wondering how to respond to it.') 
     AND option_text = 'You let the inner critic run. It keeps you sharp and motivated to do better.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), -10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You made a mistake at work today — a small one, but visible. In the hours that follow, you notice the internal voice: the one that replays the moment, questions your competence, and compares you to others who seem to handle things more easily. You know this voice well. You are wondering how to respond to it.') 
     AND option_text = 'You let the inner critic run. It keeps you sharp and motivated to do better.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), 0);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You made a mistake at work today — a small one, but visible. In the hours that follow, you notice the internal voice: the one that replays the moment, questions your competence, and compares you to others who seem to handle things more easily. You know this voice well. You are wondering how to respond to it.') 
     AND option_text = 'You let the inner critic run. It keeps you sharp and motivated to do better.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), -20);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You made a mistake at work today — a small one, but visible. In the hours that follow, you notice the internal voice: the one that replays the moment, questions your competence, and compares you to others who seem to handle things more easily. You know this voice well. You are wondering how to respond to it.' ORDER BY id DESC LIMIT 1), 'You notice the voice and ask: "What would I say to a friend who made this same mistake?"', 'This is a powerful self-compassion practice. We are almost always kinder to others than to ourselves in the same situation. Applying that same generosity to yourself is not weakness — it is emotional intelligence, and it builds the confidence that leadership requires.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You made a mistake at work today — a small one, but visible. In the hours that follow, you notice the internal voice: the one that replays the moment, questions your competence, and compares you to others who seem to handle things more easily. You know this voice well. You are wondering how to respond to it.') 
     AND option_text = 'You notice the voice and ask: "What would I say to a friend who made this same mistake?"' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), 10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You made a mistake at work today — a small one, but visible. In the hours that follow, you notice the internal voice: the one that replays the moment, questions your competence, and compares you to others who seem to handle things more easily. You know this voice well. You are wondering how to respond to it.') 
     AND option_text = 'You notice the voice and ask: "What would I say to a friend who made this same mistake?"' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), 5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You made a mistake at work today — a small one, but visible. In the hours that follow, you notice the internal voice: the one that replays the moment, questions your competence, and compares you to others who seem to handle things more easily. You know this voice well. You are wondering how to respond to it.') 
     AND option_text = 'You notice the voice and ask: "What would I say to a friend who made this same mistake?"' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), 20);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You made a mistake at work today — a small one, but visible. In the hours that follow, you notice the internal voice: the one that replays the moment, questions your competence, and compares you to others who seem to handle things more easily. You know this voice well. You are wondering how to respond to it.' ORDER BY id DESC LIMIT 1), 'You distract yourself — scroll, snack, stay busy — until the feeling passes.', 'Distraction offers temporary relief but not resolution. The inner critic returns, often louder, because it was never addressed. Noticing and naming a difficult emotion — even briefly — is more restorative than bypassing it.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You made a mistake at work today — a small one, but visible. In the hours that follow, you notice the internal voice: the one that replays the moment, questions your competence, and compares you to others who seem to handle things more easily. You know this voice well. You are wondering how to respond to it.') 
     AND option_text = 'You distract yourself — scroll, snack, stay busy — until the feeling passes.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), -5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You made a mistake at work today — a small one, but visible. In the hours that follow, you notice the internal voice: the one that replays the moment, questions your competence, and compares you to others who seem to handle things more easily. You know this voice well. You are wondering how to respond to it.') 
     AND option_text = 'You distract yourself — scroll, snack, stay busy — until the feeling passes.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), 0);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You made a mistake at work today — a small one, but visible. In the hours that follow, you notice the internal voice: the one that replays the moment, questions your competence, and compares you to others who seem to handle things more easily. You know this voice well. You are wondering how to respond to it.') 
     AND option_text = 'You distract yourself — scroll, snack, stay busy — until the feeling passes.' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), -5);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 4: The Voice' AND owner_id = (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders') LIMIT 1), 'mcq', 3, LAST_INSERT_ID());

-- ============================================
-- Card 5
-- ============================================
INSERT INTO card (owner_type, owner_id, card_order_index, title, subtitle, end_text, why_this_question) VALUES ('simulator', (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), 5, 'Phase 5: The Commitment', 'Leading from a place of balance', 'You have completed the Self-Care for Strong Leaders simulator. Your result reflects where you stand today in your relationship with your own energy, boundaries, and self-compassion. Strong leaders do not run on empty. They lead from a place of balance, awareness, and inner strength — and that place is built one intentional choice at a time.', 'This closing scenario supports integration and commitment. It helps learners move from insight to intention, and choose a concrete orientation for the days ahead. The three options represent different entry points — habit, honesty, and awareness — all of which are valid starting places for sustainable self-care leadership.');

-- Component 1 for Card 4
INSERT INTO component_image (image_url, image_alt, image_description) VALUES ('https://unsplash.com/photos/silhouette-of-woman-jumping-h7qhDX6ExD4', NULL, NULL);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 5: The Commitment' AND owner_id = (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders') LIMIT 1), 'image', 1, LAST_INSERT_ID());

-- Component 2 for Card 4
INSERT INTO component_text (content) VALUES ('You are at the end of this module. You have reflected on your energy patterns, your boundaries, your inner voice, and the habits that actually fit your life. You now have a clearer picture of what self-care means for you — not in theory, but in practice. The question is: what will you take with you when the next demanding week arrives?');
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 5: The Commitment' AND owner_id = (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders') LIMIT 1), 'text', 2, LAST_INSERT_ID());

-- Component 3 for Card 4
INSERT INTO component_mcq (question) VALUES ('You are at the end of this module. You have reflected on your energy patterns, your boundaries, your inner voice, and the habits that actually fit your life. You now have a clearer picture of what self-care means for you — not in theory, but in practice. The question is: what will you take with you when the next demanding week arrives?');
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You are at the end of this module. You have reflected on your energy patterns, your boundaries, your inner voice, and the habits that actually fit your life. You now have a clearer picture of what self-care means for you — not in theory, but in practice. The question is: what will you take with you when the next demanding week arrives?' ORDER BY id DESC LIMIT 1), 'You reflect: "I will protect at least one small moment each day that belongs entirely to me."', 'Strong commitment. One protected moment per day — however small — anchors the entire practice. It teaches you that your energy matters, and it teaches others the same. Leadership that is sustainable begins exactly here.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are at the end of this module. You have reflected on your energy patterns, your boundaries, your inner voice, and the habits that actually fit your life. You now have a clearer picture of what self-care means for you — not in theory, but in practice. The question is: what will you take with you when the next demanding week arrives?') 
     AND option_text = 'You reflect: "I will protect at least one small moment each day that belongs entirely to me."' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are at the end of this module. You have reflected on your energy patterns, your boundaries, your inner voice, and the habits that actually fit your life. You now have a clearer picture of what self-care means for you — not in theory, but in practice. The question is: what will you take with you when the next demanding week arrives?') 
     AND option_text = 'You reflect: "I will protect at least one small moment each day that belongs entirely to me."' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are at the end of this module. You have reflected on your energy patterns, your boundaries, your inner voice, and the habits that actually fit your life. You now have a clearer picture of what self-care means for you — not in theory, but in practice. The question is: what will you take with you when the next demanding week arrives?') 
     AND option_text = 'You reflect: "I will protect at least one small moment each day that belongs entirely to me."' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), 15);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You are at the end of this module. You have reflected on your energy patterns, your boundaries, your inner voice, and the habits that actually fit your life. You now have a clearer picture of what self-care means for you — not in theory, but in practice. The question is: what will you take with you when the next demanding week arrives?' ORDER BY id DESC LIMIT 1), 'You reflect: "I will try, but I know I will probably go back to old patterns when things get busy."', 'This honesty is worth honouring. Old patterns are strong — especially under pressure. What helps is not willpower, but design: a habit so small and specific that it survives even a difficult week. Start there, and build from what holds.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are at the end of this module. You have reflected on your energy patterns, your boundaries, your inner voice, and the habits that actually fit your life. You now have a clearer picture of what self-care means for you — not in theory, but in practice. The question is: what will you take with you when the next demanding week arrives?') 
     AND option_text = 'You reflect: "I will try, but I know I will probably go back to old patterns when things get busy."' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), 5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are at the end of this module. You have reflected on your energy patterns, your boundaries, your inner voice, and the habits that actually fit your life. You now have a clearer picture of what self-care means for you — not in theory, but in practice. The question is: what will you take with you when the next demanding week arrives?') 
     AND option_text = 'You reflect: "I will try, but I know I will probably go back to old patterns when things get busy."' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), 5);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are at the end of this module. You have reflected on your energy patterns, your boundaries, your inner voice, and the habits that actually fit your life. You now have a clearer picture of what self-care means for you — not in theory, but in practice. The question is: what will you take with you when the next demanding week arrives?') 
     AND option_text = 'You reflect: "I will try, but I know I will probably go back to old patterns when things get busy."' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), 10);
INSERT INTO multiple_choices_options (mcq_id, option_text, feedback) VALUES ((SELECT id FROM component_mcq WHERE question = 'You are at the end of this module. You have reflected on your energy patterns, your boundaries, your inner voice, and the habits that actually fit your life. You now have a clearer picture of what self-care means for you — not in theory, but in practice. The question is: what will you take with you when the next demanding week arrives?' ORDER BY id DESC LIMIT 1), 'You reflect: "Next time I feel depleted, I will pause and ask what I need — instead of just pushing through."', 'Excellent. This is perhaps the most powerful shift of all: from automatic pushing to deliberate pausing. That one question — "what do I need right now?" — is a complete self-care practice in itself. It reconnects you to your own intelligence.');
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are at the end of this module. You have reflected on your energy patterns, your boundaries, your inner voice, and the habits that actually fit your life. You now have a clearer picture of what self-care means for you — not in theory, but in practice. The question is: what will you take with you when the next demanding week arrives?') 
     AND option_text = 'You reflect: "Next time I feel depleted, I will pause and ask what I need — instead of just pushing through."' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), 15);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are at the end of this module. You have reflected on your energy patterns, your boundaries, your inner voice, and the habits that actually fit your life. You now have a clearer picture of what self-care means for you — not in theory, but in practice. The question is: what will you take with you when the next demanding week arrives?') 
     AND option_text = 'You reflect: "Next time I feel depleted, I will pause and ask what I need — instead of just pushing through."' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), 10);
INSERT INTO multiple_choices_options_weights (multiple_choices_options_id, simulator_metric_id, weight) VALUES ((SELECT id FROM multiple_choices_options 
     WHERE mcq_id = (SELECT id FROM component_mcq WHERE question = 'You are at the end of this module. You have reflected on your energy patterns, your boundaries, your inner voice, and the habits that actually fit your life. You now have a clearer picture of what self-care means for you — not in theory, but in practice. The question is: what will you take with you when the next demanding week arrives?') 
     AND option_text = 'You reflect: "Next time I feel depleted, I will pause and ask what I need — instead of just pushing through."' 
     ORDER BY id DESC LIMIT 1), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), 20);
INSERT INTO card_contains (card_id, component_type, component_order_index, component_id) VALUES ((SELECT id FROM card WHERE title = 'Phase 5: The Commitment' AND owner_id = (SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders') LIMIT 1), 'mcq', 3, LAST_INSERT_ID());

-- ============================================
-- Feedback Tiers
-- ============================================

-- Feedback for metric 'Energy Management' (Score 0-49)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), 0, 49, 'You are becoming aware of your energy patterns and what it feels like when your reserves are low.', 'You may override your body''s signals and keep going until depletion forces a stop. This can affect your clarity, mood, and decision-making.', 'At the end of each day, rate your energy from 1–10. After one week, look for the pattern.', NULL, 'This module can help you identify the root causes of energy drain and build a sustainable daily rhythm.');

-- Feedback for metric 'Energy Management' (Score 50-85)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), 50, 85, 'You have some practices that help you recover and maintain energy across demanding periods.', 'Under high pressure, you may still revert to pushing through rather than pausing to recharge.', 'Identify your single highest-energy moment of the day and protect it for your most important work.', NULL, 'This module can help you use energy management as a strategic leadership tool, not just a personal habit.');

-- Feedback for metric 'Energy Management' (Score 85-100)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_metric WHERE name = 'Energy Management' LIMIT 1), 85, 100, 'You manage your energy with intention and treat recovery as a non-negotiable part of your leadership.', 'None. You demonstrate strong self-awareness and sustainable performance habits.', 'Once a week, reflect on one moment when protecting your energy led to a better outcome for you or your team.', NULL, 'This module can help you extend your energy management practices into team culture and systemic leadership.');

-- Feedback for metric 'Boundaries' (Score 0-49)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), 0, 49, 'You are beginning to notice the moments when your own needs are consistently placed last.', 'You may find it difficult to say no, and may over-extend in ways that drain your energy and reduce your effectiveness over time.', 'Use a pause phrase before agreeing to any new request: "Let me check what I have capacity for."', NULL, 'This module can help you understand the relationship between boundaries, self-respect, and sustainable contribution.');

-- Feedback for metric 'Boundaries' (Score 50-85)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), 50, 85, 'You are developing the ability to protect your time and energy while remaining collaborative and supportive.', 'Under social or professional pressure, you may still soften or abandon a boundary rather than hold it calmly.', 'Practise stating a limit once, clearly and without over-explaining, and notice what happens.', NULL, 'This module can help you use boundaries as a leadership communication skill, not just a personal protection strategy.');

-- Feedback for metric 'Boundaries' (Score 85-100)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_metric WHERE name = 'Boundaries' LIMIT 1), 85, 100, 'You set clear, respectful limits and hold them even under pressure. This strengthens both your wellbeing and your credibility.', 'None. Your boundaries support your energy and make your commitments more trustworthy.', 'Identify one area where an earlier or clearer boundary would have improved a team dynamic, and use that as a model going forward.', NULL, 'This module can help you share boundary-setting as a cultural practice within your team or organisation.');

-- Feedback for metric 'Self-Compassion' (Score 0-49)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), 0, 49, 'You are beginning to notice the tone of your inner voice and how it affects your confidence and energy.', 'You may be harder on yourself than you would be on anyone else in the same situation. This can erode confidence and increase anxiety over time.', 'When you notice self-criticism, ask: "What would I say to a friend who was going through exactly this?"', NULL, 'This module can help you develop a more grounded, kind relationship with yourself as a foundation for confident leadership.');

-- Feedback for metric 'Self-Compassion' (Score 50-85)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), 50, 85, 'You are learning to treat yourself with more fairness and care, especially after setbacks or mistakes.', 'In high-pressure moments, the inner critic may still take over before you can apply self-compassion deliberately.', 'After a difficult moment, write one sentence of honest acknowledgement and one sentence of support — as if writing to yourself.', NULL, 'This module can help you build self-compassion into your leadership practice, so that resilience comes from within rather than from external validation.');

-- Feedback for metric 'Self-Compassion' (Score 85-100)
INSERT INTO simulator_feedback_tiers (simulator_id, metric_id, min_score, max_score, strength_result, risk_result, micro_practice, recommended_module_id, recommendation_reason) VALUES ((SELECT id FROM simulator WHERE title = 'Self-Care for Strong Leaders'), (SELECT id FROM simulator_metric WHERE name = 'Self-Compassion' LIMIT 1), 85, 100, 'You relate to yourself with honesty, fairness, and care. This supports your confidence, your resilience, and your ability to lead under pressure.', 'None. Your relationship with yourself is a genuine leadership strength.', 'Once a week, identify one moment when self-compassion helped you stay grounded and act more effectively.', NULL, 'This module can help you model and cultivate self-compassion in the teams and communities you lead.');

-- ============================================
-- End of generated queries
-- ============================================
