
import AppConfig from '@/config/app.config.js'
export default function getDefaultState() {
    return {
        lang: 'en',
        receivedLastPostsOn: '',
        connectedProvince: -1,
        allCatched: false,
        specialButton: {},
        searchProvAndTowns: [],
        comingUps: [],
        followings:  [],
        notifications:  [],
        blockedProfiles:  [],
        hiddenConversations:  [],
        myProvince: '',
        myBusinesses: [],
        searchCatsAndTags: [],
        headerTitle: {},
        businessDetails: [],
        profileDetails: [],
        posts: [],
        myProfile: null,
        allNews: [],
        allNewsLoaded: false,
        latestNews: [],
        categories: [],
        tags: [],
        businesses: [],
        countries: [],
        provinces: [],
        towns: [],
        allPosts: [],
        allMessages: [],
        allProfiles: [],
        serverLocation: AppConfig.API_BASE_URL, //'http://127.0.0.1:8000',
        profile: {},
        user: {},
        token: '',
        towns: [],
        provinces: [],
        flags: {
            loggedIn: false,
            screenDisabled: false,
            screenLocked: false,
        },
        myPosts: [],
        myBookmarks: [],
        allConversations: [],
        showedMessage: '',
        currentDropdownMenu: '',
        activeModule: '',
        menubarItems: {
            left: [],
            title: '',
            right: [],
            rightAsTextButtons: [],
            isRightSideMenuOpen: false,
            rightSideMenuItems: [],
        },
        allDropdownMenus: {},
        closeDialog: false,
        lastActiveDialog: '',
    }
}